package net.divinerpg;

import net.divinerpg.block.TarFluid;
import net.divinerpg.helper.CommandDivineRPG;
import net.divinerpg.helper.HelperBase;
import net.divinerpg.helper.block.OverworldBlockHelper;
import net.divinerpg.helper.handlers.DivineRPGPacketHandler;
import net.divinerpg.helper.item.OverworldItemHelper;
import net.divinerpg.helper.proxy.CommonProxyDivineRPG;
import net.divinerpg.lib.Reference;
import net.minecraft.command.ServerCommandManager;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.server.MinecraftServer;
import net.minecraftforge.fluids.Fluid;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.MOD_VERSION)
@NetworkMod(channels = { Reference.MOD_ID }, clientSideRequired = true, serverSideRequired = false, packetHandler = DivineRPGPacketHandler.class)
public class DivineRPG extends HelperBase{


	@Instance(Reference.MOD_ID)
	public static DivineRPG instance;

	@SidedProxy(serverSide = Reference.MOD_COMMON_PROXY, clientSide = Reference.MOD_CLIENT_PROXY, modId = Reference.MOD_ID)
	public static CommonProxyDivineRPG proxy;

	public static final CreativeTabs Raw = new CreativeTabs("Raw Materials"){
		public Item getTabIconItem(){
			return OverworldItemHelper.rupeeIngot; 
		}
	};    
	public static final CreativeTabs Projectile = new CreativeTabs("Projectiles"){
		public ItemStack getIconItemStack() { 
			return new ItemStack(OverworldItemHelper.scythe);
		}
	};  
	public static final CreativeTabs Spawn = new CreativeTabs("Spawner"){
		public ItemStack getIconItemStack() { 
			return new ItemStack(OverworldItemHelper.baseSpawnCrystal);
		} 
	};   
	public static final CreativeTabs Blocks = new CreativeTabs("Blocks"){
		public ItemStack getIconItemStack() { 
			return new ItemStack(OverworldBlockHelper.rupeeOre);
		}
	};  
	public static final CreativeTabs Tools = new CreativeTabs("Tools"){
		public ItemStack getIconItemStack() { 
			return new ItemStack(OverworldItemHelper.rupeeShickaxe);
		}
	};
	public static final CreativeTabs Armor = new CreativeTabs("Armor"){
		public ItemStack getIconItemStack() { 
			return new ItemStack(OverworldItemHelper.angelicHelmet);
		}
	};
	public static final CreativeTabs Swords = new CreativeTabs("Swords"){
		public ItemStack getIconItemStack() { 
			return new ItemStack(OverworldItemHelper.enderSword);
		}
	};
	public static final CreativeTabs Misc = new CreativeTabs("Misc."){
		public ItemStack getIconItemStack() { 
			return new ItemStack(OverworldItemHelper.twilightClock);
		}
	};

	public static final Fluid TarFluid = new TarFluid();
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {	  
		proxy.preInit(event);
		proxy.registerRenderInformation();
		event.getModMetadata().autogenerated = false;
		event.getModMetadata().authorList.add("DivineRPG-Team");
		event.getModMetadata().description = "Many new worlds to discover in this mod!"; //TODO extend description
		event.getModMetadata().name = "DivineRPG";
		event.getModMetadata().logoFile = logo;
		event.getModMetadata().credits = "DivineRPG Team";
		event.getModMetadata().url = "http://divinerpg.net/wiki/DivineRPG_Wiki";
		event.getModMetadata().screenshots = screenShots;
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		proxy.init(event);
		addTabName("Raw Materials");
		addTabName("Projectiles");
		addTabName("Spawner");
		addTabName("Blocks");
		addTabName("Tools");
		addTabName("Armor");
		addTabName("Swords");
		addTabName("Misc.");
	}	

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {}

	@EventHandler
	public void serverStarting(FMLServerStartingEvent event){
		if (MinecraftServer.getServer().getCommandManager() instanceof ServerCommandManager) {
			((ServerCommandManager) MinecraftServer.getServer().getCommandManager()).registerCommand(new CommandDivineRPG());
		}
	}
	
	
}
