package net.divinerpg.helper.block;

import net.divinerpg.DivineRPG;
import net.divinerpg.arcana.block.BlockAquamarine;
import net.divinerpg.arcana.block.BlockArcaniteGrass;
import net.divinerpg.arcana.block.BlockArcaniteRails;
import net.divinerpg.arcana.block.BlockArcaniteTubes;
import net.divinerpg.arcana.block.BlockDemonFurnace;
import net.divinerpg.arcana.block.BlockDramixAltar;
import net.divinerpg.arcana.block.BlockDungeonBlock;
import net.divinerpg.arcana.block.BlockEucalyptusRoot;
import net.divinerpg.arcana.block.BlockExtractinator;
import net.divinerpg.arcana.block.BlockFireStock;
import net.divinerpg.arcana.block.BlockGreenlightFurnace;
import net.divinerpg.arcana.block.BlockHeatTraps;
import net.divinerpg.arcana.block.BlockHitchak;
import net.divinerpg.arcana.block.BlockLamona;
import net.divinerpg.arcana.block.BlockMarsine;
import net.divinerpg.arcana.block.BlockMoltenFurnace;
import net.divinerpg.arcana.block.BlockMoonlightFurnace;
import net.divinerpg.arcana.block.BlockOceanfireFurnace;
import net.divinerpg.arcana.block.BlockOfLight;
import net.divinerpg.arcana.block.BlockOreDoor1;
import net.divinerpg.arcana.block.BlockOreDoor2;
import net.divinerpg.arcana.block.BlockOreDoor3;
import net.divinerpg.arcana.block.BlockOreDoor4;
import net.divinerpg.arcana.block.BlockParasectaAltar;
import net.divinerpg.arcana.block.BlockPinfly;
import net.divinerpg.arcana.block.BlockPortalArcana;
import net.divinerpg.arcana.block.BlockPortalArcanaFrame;
import net.divinerpg.arcana.block.BlockStarBridge;
import net.divinerpg.arcana.block.BlockStarBridgeOn;
import net.divinerpg.arcana.block.BlockVeilo;
import net.divinerpg.arcana.block.BlockWhitefireFurnace;
import net.divinerpg.block.BlockDivineSpawner;
import net.divinerpg.block.ModBlock;
import net.divinerpg.block.ModDirt;
import net.divinerpg.helper.HelperBase;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;

public class ArcanaBlockHelper extends HelperBase {
		
	public static final Block arcaniteDirt = new ModDirt(x.getID("ArcanaDirt")).registerTexture("ArcaniteGrass_Bottom").setUnlocalizedName("arcaniteDirt").setCreativeTab(DivineRPG.Blocks);
    public static final Block arcaniteGrass = new BlockArcaniteGrass(x.getID("ArcanaGrass")).setUnlocalizedName("ArcaniteG").setCreativeTab(DivineRPG.Blocks);
    public static final Block arcaniumOre = new ModBlock(x.getID("ArcaniumOre")).registerTexture("ArcaniumOre").setUnlocalizedName("ArcaniumOre").setCreativeTab(DivineRPG.Blocks);
    public static final BlockDemonFurnace demonFurnace = (BlockDemonFurnace)new BlockDemonFurnace(x.getID("DemonFurnace"), false).setUnlocalizedName("demonFurnace").setCreativeTab(DivineRPG.Blocks);
    public static final BlockDemonFurnace demonFurnaceOn = (BlockDemonFurnace)new BlockDemonFurnace(x.getID("DemonFurnaceOn"), true).setUnlocalizedName("DemonFurnaceOn").setCreativeTab(null);
    public static final Block starBridgeOn = new BlockStarBridgeOn(x.getID("StarBridgeOn"), true).registerTexture("StarBridgeOn").setUnlocalizedName("StarOn").setCreativeTab(null);
    public static final Block starBridge = new BlockStarBridge(x.getID("StarBridge"), false).registerTexture("StarBridge").setUnlocalizedName("Star").setCreativeTab(DivineRPG.Blocks);
    public static final BlockPortalArcanaFrame arcanaPortalFrame = (BlockPortalArcanaFrame) new BlockPortalArcanaFrame(x.getID("ArcanaPortalFrame")).setUnlocalizedName("arcanaPortalFrame").setCreativeTab(DivineRPG.Blocks);
    public static final Block extractor = new BlockExtractinator(x.getID("Extractor")).setUnlocalizedName("BlockExtractinator").setCreativeTab(DivineRPG.Blocks);
    public static final Block greenlightFurnace = new BlockGreenlightFurnace(x.getID("GreenLightFurnace"), false).setUnlocalizedName("greenlightFurnace").setCreativeTab(DivineRPG.Blocks);
    public static final Block greenlightFurnaceOn = new BlockGreenlightFurnace(x.getID("GreenLightFurnaceOn"), true).setUnlocalizedName("greenlightFurnaceOn").setCreativeTab(null);
    public static final Block heatTrapsOn = new BlockHeatTraps(x.getID("HeatTrapOn")).registerTexture("HeatTrapOn").setBlockUnbreakable().setUnlocalizedName("HeatOn").setCreativeTab(null).setCreativeTab(DivineRPG.Blocks);
    public static final Block heatTraps = new BlockHeatTraps(x.getID("HeatTrap")).registerTexture("HeatTrapOff").setBlockUnbreakable().setUnlocalizedName("Heat").setCreativeTab(DivineRPG.Blocks);
    public static final Block moltenFurnace = new BlockMoltenFurnace(x.getID("MoltenFurnace"), false).setUnlocalizedName("MoltenFurnace").setCreativeTab(DivineRPG.Blocks);
    public static final Block moltenFurnaceOn = new BlockMoltenFurnace(x.getID("MoltenFurnaceOn"), true).setUnlocalizedName("MoltenFurnaceOn").setCreativeTab(null);
    public static final Block moonlightFurnace = new BlockMoonlightFurnace(x.getID("MoonLightFurnace"), false).setUnlocalizedName("moonlightFurnace").setCreativeTab(DivineRPG.Blocks);
    public static final Block moonlightFurnaceOn = new BlockMoonlightFurnace(x.getID("MoonLightFurnaceOn"), true).setUnlocalizedName("moonlightFurnaceOn").setCreativeTab(null);
    public static final Block oceanfireFurnace = new BlockOceanfireFurnace(x.getID("OceanFireFurnace"), false).setUnlocalizedName("oceanfireFurnace").setCreativeTab(DivineRPG.Blocks);
    public static final Block oceanfireFurnaceOn = new BlockOceanfireFurnace(x.getID("OceanFireFurnaceOn"), true).setUnlocalizedName("oceanfireFurnaceOn").setCreativeTab(null);
    public static final Block whitefireFurnace = new BlockWhitefireFurnace(x.getID("WhiteFireFurnace"), false).setUnlocalizedName("whitefireFurnace").setCreativeTab(DivineRPG.Blocks);
    public static final Block whitefireFurnaceOn = new BlockWhitefireFurnace(x.getID("WhiteFireFurnaceOn"), true).setUnlocalizedName("whitefireFurnaceOn").setCreativeTab(null);
 
    public static final Block ancientBricks = new BlockDungeonBlock(x.getID("AncientBricks")).registerTexture("YellowDegradedBricks").setBlockUnbreakable().setUnlocalizedName("ancientBricks").setCreativeTab(DivineRPG.Blocks);
    public static final Block degradedBricks = new BlockDungeonBlock(x.getID("DegradedBricks")).registerTexture("DegradedBricks").setBlockUnbreakable().setUnlocalizedName("degradedBricks").setCreativeTab(DivineRPG.Blocks);
    public static final Block arcaniteMetal = new BlockDungeonBlock(x.getID("ArcaniumMetal")).registerTexture("ArcaniumMetal").setBlockUnbreakable().setUnlocalizedName("arcaniteMetal").setCreativeTab(DivineRPG.Blocks);
    public static final Block arcaniumPower = new BlockDungeonBlock(x.getID("ArcaniumPower")).registerTexture("ArcaniumPower").setBlockUnbreakable().setUnlocalizedName("arcaniumPower").setCreativeTab(DivineRPG.Blocks);
    public static final Block ancientStone = new BlockDungeonBlock(x.getID("AncientStone")).registerTexture("AncientStone").setBlockUnbreakable().setUnlocalizedName("ancientStone").setCreativeTab(DivineRPG.Blocks);
    public static final Block soulStone = new BlockDungeonBlock(x.getID("SoulStone")).registerTexture("SoulStone").setBlockUnbreakable().setUnlocalizedName("soulStone").setCreativeTab(DivineRPG.Blocks);
    public static final Block dungeonLamp = new BlockDungeonBlock(x.getID("DungeonLamp")).registerTexture("DungeonLamp").setBlockUnbreakable().setUnlocalizedName("dungeonLamp").setLightValue(1.0F).setCreativeTab(DivineRPG.Blocks);
    public static final Block ancientTile = new BlockDungeonBlock(x.getID("AncientTile")).registerTexture("AncientTile").setBlockUnbreakable().setUnlocalizedName("ancientTile").setCreativeTab(DivineRPG.Blocks);
    public static final Block soulSludge = new BlockDungeonBlock(x.getID("SoulSludge")).registerTexture("SoulSludge").setBlockUnbreakable().setUnlocalizedName("soulSludge").setCreativeTab(DivineRPG.Blocks);
    public static final Block parasectaAltar = new BlockParasectaAltar(x.getID("ParasectaAltar")).registerTexture("ParasectaAltar").setBlockUnbreakable().setUnlocalizedName("parasectaAltar").setCreativeTab(DivineRPG.Blocks);
    public static final Block dramixAltar = new BlockDramixAltar(x.getID("DramixAltar")).registerTexture("DramixAltar").setBlockUnbreakable().setUnlocalizedName("dramixAltar").setCreativeTab(DivineRPG.Blocks);
    public static final Block arcanaSpawner_Roamer = new BlockDivineSpawner(x.getID("RoamerSpawner"), "Roamer").registerTexture("ArcanaSpawner").setUnlocalizedName("arcanaSpawner Roamer").setCreativeTab(DivineRPG.Spawn);
    public static final Block arcanaSpawner_Deathcryx = new BlockDivineSpawner(x.getID("DeathcryxSpawner"), "Deathcryx").registerTexture("ArcanaSpawner").setUnlocalizedName("arcanaSpawner Deathcryx").setCreativeTab(DivineRPG.Spawn);
    public static final Block arcanaSpawner_DeathHound = new BlockDivineSpawner(x.getID("DeathHoundSpawner"), "Death Hound").registerTexture("ArcanaSpawner").setUnlocalizedName("arcanaSpawner Death Hound").setCreativeTab(DivineRPG.Spawn);
    public static final Block arcanaSpawner_Razorback = new BlockDivineSpawner(x.getID("RazorbackSpawner"), "Razorback").registerTexture("ArcanaSpawner").setUnlocalizedName("arcanaSpawner Razorback").setCreativeTab(DivineRPG.Spawn);
    public static final Block arcanaSpawner_LivingStatue = new BlockDivineSpawner(x.getID("LivingStatueSpawner"), "Living Statue").registerTexture("ArcanaSpawner").setUnlocalizedName("arcanaSpawner Living Statue").setCreativeTab(DivineRPG.Spawn);
    public static final Block arcanaSpawner_DungeonPrisoner = new BlockDivineSpawner(x.getID("DungeonPrisonerSpawner"), "Dungeon Prisoner").registerTexture("ArcanaSpawner").setUnlocalizedName("arcanaSpawner Dungeon Prisoner").setCreativeTab(DivineRPG.Spawn);
    public static final Block arcaniteTubes = new BlockArcaniteTubes(x.getID("ArcaniteTubes")).registerTexture("ArcaniteTubes").setBlockUnbreakable().setUnlocalizedName("arcaniteTubes").setCreativeTab(DivineRPG.Blocks);
    public static final Block arcaniteRails = new BlockArcaniteRails(x.getID("ArcaniteRails")).registerTexture("ArcaniumRails").setUnlocalizedName("arcaniteRails").setCreativeTab(DivineRPG.Blocks);
    public static final BlockPortalArcana arcanaPortal = (BlockPortalArcana) new BlockPortalArcana(x.getID("ArcanaPortal")).registerTexture("ArcanaPortal").setUnlocalizedName("arcanaPortal").setBlockUnbreakable().setCreativeTab(DivineRPG.Blocks);
    public static final Block blockOfLight = new BlockOfLight(x.getID("BlockOfLight")).registerTexture("BlockOfLight").setUnlocalizedName("light").setCreativeTab(DivineRPG.Blocks);
    
    public static final Block oreDoor1 = new BlockOreDoor1(x.getID("OreDoor1"), Material.iron).setCreativeTab(null).setUnlocalizedName("OreDoor1").setBlockUnbreakable().setResistance(6000000.0F);
    public static final Block oreDoor2 = new BlockOreDoor2(x.getID("OreDoor2"), Material.iron).setCreativeTab(null).setUnlocalizedName("OreDoor2").setBlockUnbreakable().setResistance(6000000.0F);
    public static final Block oreDoor3 = new BlockOreDoor3(x.getID("OreDoor3"), Material.iron).setCreativeTab(null).setUnlocalizedName("OreDoor3").setBlockUnbreakable().setResistance(6000000.0F);
    public static final Block oreDoor4 = new BlockOreDoor4(x.getID("OreDoor4"), Material.iron).setCreativeTab(null).setUnlocalizedName("OreDoor4").setBlockUnbreakable().setResistance(6000000.0F);

    public static final Block fireStock = new BlockFireStock(x.getID("FireStock")).registerTexture("Firestock_Bottom").setUnlocalizedName("FireStock").setCreativeTab(null);
    public static final Block fireStock2 = new BlockFireStock(x.getID("FireStock2")).registerTexture("Firestock_Top").setUnlocalizedName("FireStock2").setCreativeTab(null);
    public static final Block pinFly = new BlockPinfly(x.getID("PinFly")).registerTexture("Pinfly_Bottom").setUnlocalizedName("PinFly").setCreativeTab(null);
    public static final Block pinFly2 = new BlockPinfly(x.getID("PinFly2")).registerTexture("Pinfly_Top").setUnlocalizedName("PinFly2").setCreativeTab(null);
    public static final Block hitchak = new BlockHitchak(x.getID("Hitchak")).setUnlocalizedName("Hitchak").setCreativeTab(null);
    public static final Block eucalyptusRoot = new BlockEucalyptusRoot(x.getID("EucalyptusRoot")).setUnlocalizedName("EucalyptusRoot").setCreativeTab(null);
    public static final Block veilo = new BlockVeilo(x.getID("Veilo")).setUnlocalizedName("Veilo").setCreativeTab(null);
    public static final Block lamona = new BlockLamona(x.getID("Lamona")).setUnlocalizedName("Lamona").setCreativeTab(null);
    public static final Block aquamarine = new BlockAquamarine(x.getID("Aquamarine")).setUnlocalizedName("Aquamarine").setCreativeTab(null);
	public static final Block marsine = new BlockMarsine(x.getID("Marsine")).setUnlocalizedName("marsine").setCreativeTab(null);

    public static void addNames(){
    	addBlock(demonFurnaceOn, "Demon Furnace On");
    	addBlock(fireStock, "FireStock");
    	addBlock(fireStock2, "FireStock2");
    	addBlock(pinFly, "Pinfly");
    	addBlock(pinFly2, "Pinfly2");
    	addBlock(hitchak, "Hitchak");
    	addBlock(eucalyptusRoot, "Eucalyptus Roots");
    	addBlock(veilo, "Veilo");
    	addBlock(lamona, "Lamona");
    	addBlock(aquamarine, "Aquamarine");
    	addBlock(marsine, "Marsine");
		addBlock(extractor, "Extractor");
        addBlock(arcanaPortal, "Arcana Portal");
        addBlock(ancientBricks, "Ancient Bricks");
        addBlock(degradedBricks, "Degraded Bricks");
        addBlock(arcaniteMetal, "Arcanite Metal");
        addBlock(arcaniumPower, "Arcanium Power");
        addBlock(ancientStone, "Ancient Stone");
        addBlock(soulStone, "Soul Stone");
        addBlock(dungeonLamp, "Dungeon Lamp");
        addBlock(ancientTile, "Ancient Tile");
        addBlock(oreDoor1, "Ore Door1");
        addBlock(oreDoor2, "Ore Door2");
        addBlock(soulSludge, "Soul Sludge");
        addBlock(parasectaAltar, "Parasecta Altar");
        addBlock(dramixAltar, "Dramix Altar");
        addBlock(oreDoor4, "Ore Door4");
        addBlock(arcanaSpawner_Roamer, "Arcana Spawner: Roamer");
        addBlock(arcanaSpawner_DeathHound, "Arcana Spawner: Death Hound");
        addBlock(arcanaSpawner_LivingStatue, "Arcana Spawner: Living Statue");
        addBlock(arcanaSpawner_Razorback, "Arcana Spawner: Razorback");
        addBlock(arcanaSpawner_DungeonPrisoner, "Arcana Dungeon Prisoner");
        addBlock(arcanaSpawner_Deathcryx, "Arcana Spawner: Deathcryx");
        addBlock(oreDoor3, "Ore Door3");
        addBlock(arcaniteRails, "Arcanite Rails");
        addBlock(arcaniteTubes, "Arcanite Tubes");
        addBlock(heatTrapsOn, "Heat Traps On");
        addBlock(heatTraps, "Heat Traps");
        addBlock(whitefireFurnace, "Whitefire Furnace");
        addBlock(whitefireFurnaceOn, "Whitefire Furnace On");
        addBlock(oceanfireFurnace, "Oceanfire Furnace");
        addBlock(oceanfireFurnaceOn, "Oceanfire Furnace On");
        addBlock(moonlightFurnace, "Moonlight Furnace");
        addBlock(moonlightFurnaceOn, "Moonlight Furnace On");
        addBlock(moltenFurnace, "Molten Furnace");
        addBlock(moltenFurnaceOn, "Molten Furnace On");
        addBlock(greenlightFurnace, "Greenlight Furnace");
        addBlock(greenlightFurnaceOn, "Greenlight Furnace On");
        addBlock(arcanaPortalFrame, "Arcana Portal Frame");
        addBlock(starBridgeOn, "Star Bridge On");
        addBlock(starBridge, "Star Bridge");
        addBlock(arcaniteGrass, "Arcanite Grass");
        addBlock(arcaniteDirt, "Arcanite Dirt");
        addBlock(demonFurnace, "Demon Furnace");
        addBlock(arcaniumOre, "Arcanium Ore");

    }
}
