package net.divinerpg.helper.block;

import net.divinerpg.DivineRPG;
import net.divinerpg.block.BlockDivineSpawner;
import net.divinerpg.block.ModBlock;
import net.divinerpg.block.ModDirt;
import net.divinerpg.block.ModGlass;
import net.divinerpg.block.ModLeaves;
import net.divinerpg.block.ModLog;
import net.divinerpg.helper.HelperBase;
import net.divinerpg.uvite.block.BlockAzuriteVine;
import net.divinerpg.vethea.block.BlockAcid;
import net.divinerpg.vethea.block.BlockBacterialAcid;
import net.divinerpg.vethea.block.BlockBarredDoor;
import net.divinerpg.vethea.block.BlockDreamLamp;
import net.divinerpg.vethea.block.BlockDreamgrass;
import net.divinerpg.vethea.block.BlockHelioticBeam;
import net.divinerpg.vethea.block.BlockInfusionTable;
import net.divinerpg.vethea.block.BlockKarosCannon;
import net.divinerpg.vethea.block.BlockKarosHeatTileGreen;
import net.divinerpg.vethea.block.BlockKarosHeatTileRed;
import net.divinerpg.vethea.block.BlockLunicAcid;
import net.divinerpg.vethea.block.BlockPurpleFire;
import net.divinerpg.vethea.block.BlockVethea;
import net.divinerpg.vethea.block.BlockVetheaPlant;
import net.divinerpg.vethea.block.BlockVetheaPortal;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;


public class VetheaBlockHelper extends HelperBase{

	public static final Block dreamwreckerSpawner = new BlockDivineSpawner(x.getID("DreamWreckerSpawner"), "Dreamwrecker").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
	public static final Block vermenousSpawner = new BlockDivineSpawner(x.getID("VermenousSpawner"), "Vermenous").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
	public static final Block twinsSpawner = new BlockDivineSpawner(x.getID("TwinsSpawner"), "Twins").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
	public static final Block biphronSpawner = new BlockDivineSpawner(x.getID("BiphronSpawner"), "Biphron").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
	public static final Block gorgosionSpawner = new BlockDivineSpawner(x.getID("GorgosionSpawner"), "Gorgosion").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);

	public static final Block wreckAltar = new ModBlock(x.getID("WreckAltar")).registerTexture("WreckAltar").setCreativeTab(DivineRPG.Spawn);
	public static final Block quadroticAltar = new ModBlock(x.getID("QuadroticAltar")).registerTexture("QuadroticAltar").setCreativeTab(DivineRPG.Spawn);
	public static final Block karosAltar = new ModBlock(x.getID("KarosAltar")).registerTexture("KarosAltar").setCreativeTab(DivineRPG.Spawn);
	public static final Block raglokAltar = new ModBlock(x.getID("RaglokAltar")).registerTexture("RaglokAltar").setCreativeTab(DivineRPG.Spawn);
	public static final BlockVetheaPortal vetheaPortal = (BlockVetheaPortal)new BlockVetheaPortal(x.getID("VetheaPortal")).registerTexture("VetheaPortal").setCreativeTab(DivineRPG.Blocks).setUnlocalizedName("VetheaPortal").setBlockUnbreakable();
	public static final Block lunicAltar = new ModBlock(x.getID("LunicAltar")).registerTexture("LunicAltar").setUnlocalizedName("Lunic").setCreativeTab(DivineRPG.Spawn);

	public static final Block dreamStone = new ModBlock(x.getID("DreamStone")).registerTexture("HungerStone1").setUnlocalizedName("dreamstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreamDirt = new ModDirt(x.getID("DreamDirt")).registerTexture("DreamGrass_Bottom").setUnlocalizedName("dreamdirt").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreamGrass = new BlockDreamgrass(x.getID("DreamGrass")).setUnlocalizedName("dreamgrass").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block fireCrystal = new ModBlock(x.getID("FireCrystal")).registerTexture("FireCrystal").setLightValue(0.7F).setUnlocalizedName("firecrystal").setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Blocks);

	public static final Block dreamwood = new ModLog(x.getID("DreamWood"), "DreamWood").setUnlocalizedName("DreamWood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreamwoodLeaves = new ModLeaves(x.getID("DreamWoodLeaves"), "DreamWood").setUnlocalizedName("dreamwoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreambricks = new BlockVethea(x.getID("DreamBricks"), Material.rock).registerTexture("DreamBricks1").setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block lunastone = new BlockVethea(x.getID("LunaStone"), Material.rock).registerTexture("LunaStone").setBlockUnbreakable().setUnlocalizedName("lunastone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block lunabricks = new BlockVethea(x.getID("LunaBricks"), Material.rock).registerTexture("LunaBrick").setBlockUnbreakable().setUnlocalizedName("lunabricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block metalCaging = new BlockVethea(x.getID("MetalCaging"), Material.rock).registerTexture("MetalCaging").setUnlocalizedName("metalCaging").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreamlampOn = new BlockDreamLamp(x.getID("DreamLampOn"), 30, Material.glass, true).registerTexture("DreamLamp_On").setBlockUnbreakable().setUnlocalizedName("dreamlampOn").setHardness(1F).setResistance(1F).setLightValue(1.0F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreamlamp = new BlockDreamLamp(x.getID("DreamLamp"), 31, Material.glass, false).registerTexture("DreamLamp_Off").setBlockUnbreakable().setUnlocalizedName("dreamlamp").setHardness(1F).setStepSound(Block.soundGlassFootstep).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block weedwoodVine = new BlockAzuriteVine(x.getID("WeedWoodVine"), "WeedWood").setUnlocalizedName("WeedWoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block blossomingWeedwoodVine = new BlockAzuriteVine(x.getID("BlossomingWeedWoodVine"), "WeedWoodBlossomed").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block cryptWall = new BlockVethea(x.getID("CryptWall"), Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("cryptWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block smoothGlass = new ModGlass(x.getID("SmoothGlass")).registerTexture("SmoothGlass").setStepSound(Block.soundGlassFootstep).setUnlocalizedName("smoothGlass").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block villageLamp = new BlockVethea(x.getID("VillageLamp"), Material.glass).registerTexture("VillageLamp").setUnlocalizedName("villageLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block cellLamp = new BlockVethea(x.getID("CellLamp"), Material.glass).registerTexture("CellLamp").setUnlocalizedName("cellLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block barredDoor = new BlockBarredDoor(x.getID("BarredDoor"), Material.wood, "BarredDoor").setUnlocalizedName("barredDoor").setHardness(1F).setResistance(1F).setCreativeTab(null);
	public static final Block firelight = new BlockVethea(x.getID("FireLight"), Material.glass).registerTexture("FireLight").setUnlocalizedName("firelight").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setResistance(1.0F).setCreativeTab(DivineRPG.Blocks);
	public static final Block hyrewood = new ModLog(x.getID("HyreWood"), "HyreWood").setUnlocalizedName("hyrewood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block mintwoodLeaves = new ModLeaves(x.getID("MintWoodLeaves"), "MintWood").setUnlocalizedName("mintwoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block firewall = new BlockVethea(x.getID("FireWall"), Material.rock).registerTexture("FireWall").setUnlocalizedName("firewall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block karosHeatTileGreen = new BlockKarosHeatTileGreen(x.getID("KarosHeatTileGreen"), false).registerTexture("KarosHeatTile1").setBlockUnbreakable().setUnlocalizedName("karosHeatTileGreen").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block karosHeatTileRed = new BlockKarosHeatTileRed(x.getID("KarosHeatTileRed"), true).registerTexture("KarosHeatTile2").setBlockUnbreakable().setUnlocalizedName("karosHeatTileRed").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block firewood = new ModLog(x.getID("FireWood"), "FireWood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block bacterialAcid = new BlockBacterialAcid(x.getID("BacterialAcid")).registerTexture("VetheaPortal").setUnlocalizedName("bacterialAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block blockAcid = new BlockAcid(x.getID("BlockAcid")).registerTexture("VetheaPortal").setUnlocalizedName("blockAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block everstone = new BlockVethea(x.getID("EverStone"), Material.rock).registerTexture("GreenEverstone").setBlockUnbreakable().setUnlocalizedName("everstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block lunicAcid = new BlockLunicAcid(x.getID("LunicAcid"), 141).registerTexture("VetheaPortal").setUnlocalizedName("lunicAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block firewoodLeaves = new ModLeaves(x.getID("FireWoodLeaves"), "FireWood").setUnlocalizedName("firewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block hyrewoodLeaves = new ModLeaves(x.getID("HyreWoodLeaves"), "HyreWood").setUnlocalizedName("hyrewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block gemtopGreen = new BlockVetheaPlant(x.getID("GemTopGreen")).registerTexture("GreenGemTop").setUnlocalizedName("gemtopGreen").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block gemtopPurple = new BlockVetheaPlant(x.getID("GemTopPurple")).registerTexture("PurpleGemTop").setUnlocalizedName("gemtopPurple").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block yellowDulah = new BlockVetheaPlant(x.getID("YellowDulah")).registerTexture("YellowDulah").setUnlocalizedName("yellowDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block greenDulah = new BlockVetheaPlant(x.getID("GreenDulah")).registerTexture("GreenDulah").setUnlocalizedName("greenDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block mintwood = new ModLog(x.getID("MintWood"), "MintWood").setUnlocalizedName("mint").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block lightFirewoodLeaves = new ModLeaves(x.getID("LightFireWoodLeaves"), "FireWood").setUnlocalizedName("lightFirewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block cracklespike = new BlockVetheaPlant(x.getID("CrackleSpike")).registerTexture("CrackleSpike").setUnlocalizedName("cracklespike").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block fernite = new BlockVetheaPlant(x.getID("Fernite")).registerTexture("Fernite").setUnlocalizedName("Fernite").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block bulatobe = new BlockVetheaPlant(x.getID("Bulatobe")).registerTexture("Bulbatobe").setUnlocalizedName("Bulbatobe").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block shineGrass = new BlockVetheaPlant(x.getID("ShineGrass")).registerTexture("ShineGrass").setUnlocalizedName("ShineGrass").setLightValue(0.4F).setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	//public static final Block shimmer = new BlockShimmer(x.getID("Shimmer).setLightValue(0.4F).setUnlocalizedName("shimmer").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block hiveWall = new BlockVethea(x.getID("HiveWall"), Material.glass).registerTexture("HiveWalls").setLightValue(0.533F).setUnlocalizedName("dreamlampOn").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	//public static final Block dreamglow = new BlockShimmer(x.getID("Dreamglow).setLightValue(0.4F).setUnlocalizedName("dreamglow").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block hyrewoodVine = new BlockAzuriteVine(x.getID("HyreWoodVine"), "WeedWood").setUnlocalizedName("hyrewoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreambricks2 = new BlockVethea(x.getID("DreamBricks2"), Material.rock).registerTexture("DreamBricks2").setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block chamberWall = new BlockVethea(x.getID("ChamberWall"), Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("chamberWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block chamberWall1 = new BlockVethea(x.getID("ChamberWall1"), Material.rock).registerTexture("ChamberWall2").setBlockUnbreakable().setUnlocalizedName("chamberWall1").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block chamberWall2 = new BlockVethea(x.getID("ChamberWall2"), Material.rock).registerTexture("ChamberWall3").setBlockUnbreakable().setUnlocalizedName("chamberWall2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block whiteEverstone = new BlockVethea(x.getID("WhiteEverStone"), Material.rock).registerTexture("WhiteEverstone").setBlockUnbreakable().setUnlocalizedName("whiteEverstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block darkEverstone = new BlockVethea(x.getID("DarkEverStone"), Material.rock).registerTexture("DarkEverstone").setBlockUnbreakable().setUnlocalizedName("darkEverstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block infusionTable = new BlockInfusionTable(x.getID("InfusionTable")).setBlockUnbreakable().setUnlocalizedName("infusionTable").setBlockUnbreakable().setResistance(999F).setCreativeTab(DivineRPG.Blocks);
	public static final Block hungerstone1 = new BlockVethea(x.getID("HungerStone1"), Material.rock).registerTexture("HungerStone1").setUnlocalizedName("hungerstone1").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block hungerstone2 = new BlockVethea(x.getID("HungerStone2"), Material.rock).registerTexture("HungerStone2").setUnlocalizedName("hungerstone2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block cryptFloor = new BlockVethea(x.getID("CryptFloor"), Material.rock).registerTexture("CryptFloor").setBlockUnbreakable().setUnlocalizedName("cryptFloor").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block hallWall = new BlockVethea(x.getID("HallWall"), Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("hallWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block karosBricks = new BlockVethea(x.getID("KarosBricks"), Material.rock).registerTexture("KarosBrick").setBlockUnbreakable().setUnlocalizedName("karosBricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block karosBricks2 = new BlockVethea(x.getID("KarosBricks2"), Material.rock).registerTexture("KarosBrick").setBlockUnbreakable().setUnlocalizedName("karosBricks2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final BlockHelioticBeam helioticBeam = (BlockHelioticBeam) new BlockHelioticBeam(x.getID("HelioticBeam")).registerTexture("HelioticBeam_Side", "HelioticBeam_Top", "HelioticBeam_Top").setUnlocalizedName("helioticBeam").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final BlockKarosCannon karosCannon = (BlockKarosCannon) new BlockKarosCannon(x.getID("KarosCannon"), Material.rock).registerTexture("KarosCannon").setBlockUnbreakable().setUnlocalizedName("karosCannon").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block purpleFire = new BlockPurpleFire(x.getID("PurpleFire")).setUnlocalizedName("purpleFire");




	public static void addNames() {
		addBlock(gorgosionSpawner, "Gorgosion Spawner");
		addBlock(biphronSpawner, "Biphron Spawner");
		addBlock(twinsSpawner, "Twins Spawner");
		addBlock(dreamwreckerSpawner, "Dreamwrecker Spawner");
		addBlock(vermenousSpawner, "Vermenous Spawner");
		addBlock(vetheaPortal, "Vethea Portal");
		addBlock(dreamStone, "Dreamstone");
		addBlock(dreamGrass, "Dream Grass");
		addBlock(dreamDirt, "Dream Dirt");
		addBlock(dreamwood, "Dreamwood");
		addBlock(dreamwoodLeaves, "Dreamwood Leaves");
		addBlock(dreambricks, "Dreambricks");
		addBlock(dreambricks2, "Dreambricks");
		addBlock(lunastone, "Lunastone");
		addBlock(metalCaging, "Metal Caging");
		addBlock(weedwoodVine, "Weedwood Vines");
		addBlock(blossomingWeedwoodVine, "Blossoming Weedwood Vines");
		addBlock(cryptWall, "Crypt Wall");
		addBlock(smoothGlass, "Smooth Glass");
		addBlock(villageLamp, "Altar Lamps");
		addBlock(infusionTable, "Infusion Table");
		addBlock(cellLamp, "Cell Lamp");
		addBlock(barredDoor, "Barred Door");
		addBlock(fireCrystal, "Firecrystal");
		addBlock(firelight, "Firelight");
		addBlock(hyrewood, "Hyrewood");
		addBlock(mintwoodLeaves, "Mintwood Leaves");
		addBlock(firewall, "Firewall");
		addBlock(karosHeatTileGreen, "Karos Heat Tile");
		addBlock(karosHeatTileRed, "Karos Heat Tile");
		addBlock(karosCannon, "Karos Cannon");
		addBlock(helioticBeam, "Heliotic Beam");
		addBlock(cryptFloor, "Crypt Floor");
		addBlock(firewood, "Firewood");
		addBlock(chamberWall, "Chamber Wall");
		addBlock(chamberWall1, "Chamber Wall");
		addBlock(chamberWall2, "Chamber Wall");
		addBlock(karosBricks, "Karos Bricks");
		addBlock(karosBricks2, "Karos Bricks");
		addBlock(bacterialAcid, "Bacterial Acid");
		addBlock(hungerstone1, "Hungerstone");
		addBlock(hungerstone2, "Hungerstone");
		addBlock(blockAcid, "Acid");
		addBlock(hallWall, "Hall Wall");
		addBlock(wreckAltar, "Wreck Altar");
		addBlock(raglokAltar, "Raglok Altar");
		addBlock(karosAltar, "Karos Altar");
		addBlock(lunicAltar, "Lunic Altar");
		addBlock(quadroticAltar, "Quadrotic Altar");
		addBlock(hiveWall, "Hive Walls");
		addBlock(darkEverstone, "Dark Everstone");
		addBlock(whiteEverstone, "White Everstone");
		addBlock(everstone, "Everstone");
		addBlock(lunicAcid, "Lunic Acid");
		addBlock(firewoodLeaves, "Firewood Leaves");
		addBlock(hyrewoodLeaves, "Hyrewood Leaves");
		addBlock(gemtopGreen, "Green Gemtops");
		addBlock(gemtopPurple, "Purple Gemtops");
		addBlock(yellowDulah, "Yellow Dulahs");
		addBlock(greenDulah, "Green Dulahs");
		addBlock(mintwood, "Mintwood");
		addBlock(lightFirewoodLeaves, "Light Firewood Leaves");
		addBlock(cracklespike, "Crackle Spikes");
		addBlock(fernite, "Fernites");
		addBlock(bulatobe, "Bulbatobes");
		addBlock(shineGrass, "Shine Grass");
		//addBlock(shimmer, "Shimmers");
		//addBlock(dreamglow, "Dream Glows");
		addBlock(hyrewoodVine, "Hyrewood Vines");
	}

}
