package net.divinerpg.helper.block;

import net.divinerpg.DivineRPG;
import net.divinerpg.block.BlockDivineSpawner;
import net.divinerpg.block.ModBlock;
import net.divinerpg.block.ModDirt;
import net.divinerpg.block.ModGlass;
import net.divinerpg.block.ModLeaves;
import net.divinerpg.block.ModLog;
import net.divinerpg.helper.HelperBase;
import net.divinerpg.helper.config.VetheaConfigHelper;
import net.divinerpg.uvite.block.BlockAzuriteVine;
import net.divinerpg.vethea.block.*;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;


public class VetheaBlockHelper extends HelperBase{

    public static final Block dreamwreckerSpawner = new BlockDivineSpawner(z.dreamwreckerSpawnerID, "Dreamwrecker").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
    public static final Block vermenousSpawner = new BlockDivineSpawner(z.vermenousSpawnerID, "Vermenous").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
    public static final Block twinsSpawner = new BlockDivineSpawner(z.twinsSpawnerID, "Twins").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
    public static final Block biphronSpawner = new BlockDivineSpawner(z.biphronSpawnerID, "Biphron").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
    public static final Block gorgosionSpawner = new BlockDivineSpawner(z.gorgosionSpawnerID, "Gorgosion").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
    
    public static final Block wreckAltar = new ModBlock(z.wreckAltarID).registerTexture("WreckAltar").setCreativeTab(DivineRPG.Spawn);
    public static final Block quadroticAltar = new ModBlock(z.quadroticAltarID).registerTexture("QuadroticAltar").setCreativeTab(DivineRPG.Spawn);
    public static final Block karosAltar = new ModBlock(z.karosAltarID).registerTexture("KarosAltar").setCreativeTab(DivineRPG.Spawn);
    public static final Block raglokAltar = new ModBlock(z.raglokAltarID).registerTexture("RaglokAltar").setCreativeTab(DivineRPG.Spawn);
    public static final BlockVetheaPortal vetheaPortal = (BlockVetheaPortal)new BlockVetheaPortal(z.vetheaPortalID).registerTexture("VetheaPortal").setCreativeTab(DivineRPG.Blocks).setUnlocalizedName("VetheaPortal").setBlockUnbreakable();
    public static final Block lunicAltar = new ModBlock(z.lunicAltarID).registerTexture("LunicAltar").setUnlocalizedName("Lunic").setCreativeTab(DivineRPG.Spawn);

    public static final Block dreamStone = new ModBlock(z.dreamstoneID).registerTexture("HungerStone1").setUnlocalizedName("dreamstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block dreamDirt = new ModDirt(z.DreamDirtID).registerTexture("DreamGrass_Bottom").setUnlocalizedName("dreamdirt").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block dreamGrass = new BlockDreamgrass(z.DreamGrassID).setUnlocalizedName("dreamgrass").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block fireCrystal = new ModBlock(z.firecrystalID).registerTexture("FireCrystal").setLightValue(0.7F).setUnlocalizedName("firecrystal").setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Blocks);

    public static final Block dreamwood = new ModLog(z.dreamwoodID, "DreamWood").setUnlocalizedName("dreamwood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block dreamwoodLeaves = new ModLeaves(z.dreamwoodLeavesID, "DreamWood").setUnlocalizedName("dreamwoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block dreambricks = new BlockVethea(z.dreambricksID, Material.rock).registerTexture("DreamBricks1").setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block lunastone = new BlockVethea(z.lunastoneID, Material.rock).registerTexture("LunaStone").setBlockUnbreakable().setUnlocalizedName("lunastone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block lunabricks = new BlockVethea(z.lunabricksID, Material.rock).registerTexture("LunaBrick").setBlockUnbreakable().setUnlocalizedName("lunabricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block metalCaging = new BlockVethea(z.metalCagingID, Material.rock).registerTexture("MetalCaging").setUnlocalizedName("metalCaging").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block dreamlampOn = new BlockDreamLamp(z.dreamlampOnID, 30, Material.glass, true).registerTexture("DreamLamp_On").setBlockUnbreakable().setUnlocalizedName("dreamlampOn").setHardness(1F).setResistance(1F).setLightValue(1.0F).setCreativeTab(DivineRPG.Blocks);
    public static final Block dreamlamp = new BlockDreamLamp(z.dreamlampID, 31, Material.glass, false).registerTexture("DreamLamp_Off").setBlockUnbreakable().setUnlocalizedName("dreamlamp").setHardness(1F).setStepSound(Block.soundGlassFootstep).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block weedwoodVine = new BlockAzuriteVine(z.weedwoodVineID, "WeedWood").setUnlocalizedName("weedwoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block blossomingWeedwoodVine = new BlockAzuriteVine(z.blossomingWeedwoodVineID, "WeedWoodBlossomed").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block cryptWall = new BlockVethea(z.cryptWallID, Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("cryptWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block smoothGlass = new ModGlass(z.smoothGlassID).registerTexture("SmoothGlass").setStepSound(Block.soundGlassFootstep).setUnlocalizedName("smoothGlass").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block villageLamp = new BlockVethea(z.villageLampID, Material.glass).registerTexture("VillageLamp").setUnlocalizedName("villageLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block cellLamp = new BlockVethea(z.cellLampID, Material.glass).registerTexture("CellLamp").setUnlocalizedName("cellLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block barredDoor = new BlockBarredDoor(z.barredDoorID, Material.wood, "BarredDoor").setUnlocalizedName("barredDoor").setHardness(1F).setResistance(1F).setCreativeTab(null);
    public static final Block firelight = new BlockVethea(z.firelightID, Material.glass).registerTexture("FireLight").setUnlocalizedName("firelight").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setResistance(1.0F).setCreativeTab(DivineRPG.Blocks);
    public static final Block hyrewood = new ModLog(z.hyrewoodID, "HyreWood").setUnlocalizedName("hyrewood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block mintwoodLeaves = new ModLeaves(z.mintwoodLeavesID, "MintWood").setUnlocalizedName("mintwoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block firewall = new BlockVethea(z.firewallID, Material.rock).registerTexture("FireWall").setUnlocalizedName("firewall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block karosHeatTileGreen = new BlockKarosHeatTileGreen(z.karosHeatTileGreenID, false).registerTexture("KarosHeatTile1").setBlockUnbreakable().setUnlocalizedName("karosHeatTileGreen").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block karosHeatTileRed = new BlockKarosHeatTileRed(z.karosHeatTileRedID, true).registerTexture("KarosHeatTile2").setBlockUnbreakable().setUnlocalizedName("karosHeatTileRed").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block firewood = new ModLog(z.firewoodID, "FireWood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block bacterialAcid = new BlockBacterialAcid(z.bacterialAcidID).registerTexture("VetheaPortal").setUnlocalizedName("bacterialAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block blockAcid = new BlockAcid(z.blockAcidID).registerTexture("VetheaPortal").setUnlocalizedName("blockAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block everstone = new BlockVethea(z.everstoneID, Material.rock).registerTexture("GreenEverstone").setBlockUnbreakable().setUnlocalizedName("everstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block lunicAcid = new BlockLunicAcid(z.lunicAcidID, 141).registerTexture("VetheaPortal").setUnlocalizedName("lunicAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block firewoodLeaves = new ModLeaves(z.firewoodLeavesID, "FireWood").setUnlocalizedName("firewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block hyrewoodLeaves = new ModLeaves(z.hyrewoodLeavesID, "HyreWood").setUnlocalizedName("hyrewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block gemtopGreen = new BlockVetheaPlant(z.gemtopGreenID).registerTexture("GreenGemTop").setUnlocalizedName("gemtopGreen").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
    public static final Block gemtopPurple = new BlockVetheaPlant(z.gemtopPurpleID).registerTexture("PurpleGemTop").setUnlocalizedName("gemtopPurple").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
    public static final Block yellowDulah = new BlockVetheaPlant(z.yellowDulahID).registerTexture("YellowDulah").setUnlocalizedName("yellowDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
    public static final Block greenDulah = new BlockVetheaPlant(z.greenDulahID).registerTexture("GreenDulah").setUnlocalizedName("greenDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
    public static final Block mintwood = new ModLog(z.mintwoodID, "MintWood").setUnlocalizedName("mint").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block lightFirewoodLeaves = new ModLeaves(z.lightFirewoodLeavesID, "FireWood").setUnlocalizedName("lightFirewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block cracklespike = new BlockVetheaPlant(z.cracklespikeID).registerTexture("CrackleSpike").setUnlocalizedName("cracklespike").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
    public static final Block fernite = new BlockVetheaPlant(z.ferniteID).registerTexture("Fernite").setUnlocalizedName("Fernite").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
    public static final Block bulatobe = new BlockVetheaPlant(z.bulatobeID).registerTexture("Bulbatobe").setUnlocalizedName("Bulbatobe").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
    public static final Block shineGrass = new BlockVetheaPlant(z.shineGrassID).registerTexture("ShineGrass").setUnlocalizedName("ShineGrass").setLightValue(0.4F).setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
    //public static final Block shimmer = new BlockShimmer(z.shimmerID).setLightValue(0.4F).setUnlocalizedName("shimmer").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
    public static final Block hiveWall = new BlockVethea(z.hiveWallID, Material.glass).registerTexture("HiveWalls").setLightValue(0.533F).setUnlocalizedName("dreamlampOn").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    //public static final Block dreamglow = new BlockShimmer(z.dreamglowID).setLightValue(0.4F).setUnlocalizedName("dreamglow").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
    public static final Block hyrewoodVine = new BlockAzuriteVine(z.hyrewoodVineID, "WeedWood").setUnlocalizedName("hyrewoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block dreambricks2 = new BlockVethea(z.dreambricks2ID, Material.rock).registerTexture("DreamBricks2").setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block chamberWall = new BlockVethea(z.chamberWallID, Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("chamberWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block chamberWall1 = new BlockVethea(z.chamberWall1ID, Material.rock).registerTexture("ChamberWall2").setBlockUnbreakable().setUnlocalizedName("chamberWall1").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block chamberWall2 = new BlockVethea(z.chamberWall2ID, Material.rock).registerTexture("ChamberWall3").setBlockUnbreakable().setUnlocalizedName("chamberWall2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block whiteEverstone = new BlockVethea(z.whiteEverstoneID, Material.rock).registerTexture("WhiteEverstone").setBlockUnbreakable().setUnlocalizedName("whiteEverstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block darkEverstone = new BlockVethea(z.darkEverstoneID, Material.rock).registerTexture("DarkEverstone").setBlockUnbreakable().setUnlocalizedName("darkEverstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block infusionTable = new BlockInfusionTable(z.infusionTableID).setBlockUnbreakable().setUnlocalizedName("infusionTable").setBlockUnbreakable().setResistance(999F).setCreativeTab(DivineRPG.Blocks);
    public static final Block hungerstone1 = new BlockVethea(z.hungerstone1ID, Material.rock).registerTexture("HungerStone1").setUnlocalizedName("hungerstone1").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block hungerstone2 = new BlockVethea(z.hungerstone2ID, Material.rock).registerTexture("HungerStone2").setUnlocalizedName("hungerstone2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block cryptFloor = new BlockVethea(z.cryptFloorID, Material.rock).registerTexture("CryptFloor").setBlockUnbreakable().setUnlocalizedName("cryptFloor").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block hallWall = new BlockVethea(z.hallWallID, Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("hallWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block karosBricks = new BlockVethea(z.karosBricksID, Material.rock).registerTexture("KarosBrick").setBlockUnbreakable().setUnlocalizedName("karosBricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block karosBricks2 = new BlockVethea(z.karosBricks2ID, Material.rock).registerTexture("KarosBrick").setBlockUnbreakable().setUnlocalizedName("karosBricks2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final BlockHelioticBeam helioticBeam = (BlockHelioticBeam) new BlockHelioticBeam(z.helioticBeamID).registerTexture("HelioticBeam_Side", "HelioticBeam_Top", "HelioticBeam_Top").setUnlocalizedName("helioticBeam").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final BlockKarosCannon karosCannon = (BlockKarosCannon) new BlockKarosCannon(z.karosCannonID, Material.rock).registerTexture("KarosCannon").setBlockUnbreakable().setUnlocalizedName("karosCannon").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
    public static final Block purpleFire = new BlockPurpleFire(z.purpleFireID).setUnlocalizedName("purpleFire");
     

    public static void addNames()
    {
    	addBlock(gorgosionSpawner, "Gorgosion Spawner");
    	addBlock(biphronSpawner, "Biphron Spawner");
    	addBlock(twinsSpawner, "Twins Spawner");
    	addBlock(dreamwreckerSpawner, "Dreamwrecker Spawner");
    	addBlock(vermenousSpawner, "Vermenous Spawner");
       addBlock(vetheaPortal, "Vethea Portal");
       addBlock(dreamStone, "Dreamstone");
       addBlock(dreamGrass, "Dream Grass");
       addBlock(dreamDirt, "Dream Dirt");
       addBlock(dreamwood, "Dreamwood");
       addBlock(dreamwoodLeaves, "Dreamwood Leaves");
       addBlock(dreambricks, "Dreambricks");
       addBlock(dreambricks2, "Dreambricks");
       addBlock(lunastone, "Lunastone");
       addBlock(metalCaging, "Metal Caging");
       addBlock(weedwoodVine, "Weedwood Vines");
       addBlock(blossomingWeedwoodVine, "Blossoming Weedwood Vines");
       addBlock(cryptWall, "Crypt Wall");
       addBlock(smoothGlass, "Smooth Glass");
       addBlock(villageLamp, "Altar Lamps");
       addBlock(infusionTable, "Infusion Table");
       addBlock(cellLamp, "Cell Lamp");
       addBlock(barredDoor, "Barred Door");
       addBlock(fireCrystal, "Firecrystal");
       addBlock(firelight, "Firelight");
       addBlock(hyrewood, "Hyrewood");
       addBlock(mintwoodLeaves, "Mintwood Leaves");
       addBlock(firewall, "Firewall");
       addBlock(karosHeatTileGreen, "Karos Heat Tile");
       addBlock(karosHeatTileRed, "Karos Heat Tile");
       addBlock(karosCannon, "Karos Cannon");
       addBlock(helioticBeam, "Heliotic Beam");
       addBlock(cryptFloor, "Crypt Floor");
       addBlock(firewood, "Firewood");
       addBlock(chamberWall, "Chamber Wall");
       addBlock(chamberWall1, "Chamber Wall");
       addBlock(chamberWall2, "Chamber Wall");
       addBlock(karosBricks, "Karos Bricks");
       addBlock(karosBricks2, "Karos Bricks");
       addBlock(bacterialAcid, "Bacterial Acid");
       addBlock(hungerstone1, "Hungerstone");
       addBlock(hungerstone2, "Hungerstone");
       addBlock(blockAcid, "Acid");
       addBlock(hallWall, "Hall Wall");
       addBlock(wreckAltar, "Wreck Altar");
       addBlock(raglokAltar, "Raglok Altar");
       addBlock(karosAltar, "Karos Altar");
       addBlock(lunicAltar, "Lunic Altar");
       addBlock(quadroticAltar, "Quadrotic Altar");
       addBlock(hiveWall, "Hive Walls");
       addBlock(darkEverstone, "Dark Everstone");
       addBlock(whiteEverstone, "White Everstone");
       addBlock(everstone, "Everstone");
       addBlock(lunicAcid, "Lunic Acid");
       addBlock(firewoodLeaves, "Firewood Leaves");
       addBlock(hyrewoodLeaves, "Hyrewood Leaves");
       addBlock(gemtopGreen, "Green Gemtops");
       addBlock(gemtopPurple, "Purple Gemtops");
       addBlock(yellowDulah, "Yellow Dulahs");
       addBlock(greenDulah, "Green Dulahs");
       addBlock(mintwood, "Mintwood");
       addBlock(lightFirewoodLeaves, "Light Firewood Leaves");
       addBlock(cracklespike, "Crackle Spikes");
       addBlock(fernite, "Fernites");
       addBlock(bulatobe, "Bulbatobes");
       addBlock(shineGrass, "Shine Grass");
       //addBlock(shimmer, "Shimmers");
       //addBlock(dreamglow, "Dream Glows");
       addBlock(hyrewoodVine, "Hyrewood Vines");
    }

}
