package net.divinerpg.helper.block;

import net.divinerpg.DivineRPG;
import net.divinerpg.block.BlockDivineSpawner;
import net.divinerpg.block.ModBlock;
import net.divinerpg.block.ModDirt;
import net.divinerpg.block.ModGlass;
import net.divinerpg.block.ModLeaves;
import net.divinerpg.block.ModLog;
import net.divinerpg.helper.HelperBase;
import net.divinerpg.helper.config.VetheaConfigHelper;
import net.divinerpg.uvite.block.BlockAzuriteVine;
import net.divinerpg.vethea.block.*;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;


public class VetheaBlockHelper extends HelperBase{

	public static final Block dreamwreckerSpawner = new BlockDivineSpawner(b.dreamwreckerSpawnerID, "Dreamwrecker").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
	public static final Block vermenousSpawner = new BlockDivineSpawner(b.vermenousSpawnerID, "Vermenous").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
	public static final Block twinsSpawner = new BlockDivineSpawner(b.twinsSpawnerID, "Twins").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
	public static final Block biphronSpawner = new BlockDivineSpawner(b.biphronSpawnerID, "Biphron").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);
	public static final Block gorgosionSpawner = new BlockDivineSpawner(b.gorgosionSpawnerID, "Gorgosion").registerTexture("FireCrystal").setCreativeTab(DivineRPG.Spawn);

	public static final Block wreckAltar = new ModBlock(b.wreckAltarID).registerTexture("WreckAltar").setCreativeTab(DivineRPG.Spawn);
	public static final Block quadroticAltar = new ModBlock(b.quadroticAltarID).registerTexture("QuadroticAltar").setCreativeTab(DivineRPG.Spawn);
	public static final Block karosAltar = new ModBlock(b.karosAltarID).registerTexture("KarosAltar").setCreativeTab(DivineRPG.Spawn);
	public static final Block raglokAltar = new ModBlock(b.raglokAltarID).registerTexture("RaglokAltar").setCreativeTab(DivineRPG.Spawn);
	public static final BlockVetheaPortal vetheaPortal = (BlockVetheaPortal)new BlockVetheaPortal(b.vetheaPortalID).registerTexture("VetheaPortal").setCreativeTab(DivineRPG.Blocks).setUnlocalizedName("VetheaPortal").setBlockUnbreakable();
	public static final Block lunicAltar = new ModBlock(b.lunicAltarID).registerTexture("LunicAltar").setUnlocalizedName("Lunic").setCreativeTab(DivineRPG.Spawn);

	public static final Block dreamStone = new ModBlock(b.dreamstoneID).registerTexture("HungerStone1").setUnlocalizedName("dreamstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreamDirt = new ModDirt(b.DreamDirtID).registerTexture("DreamGrass_Bottom").setUnlocalizedName("dreamdirt").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreamGrass = new BlockDreamgrass(b.DreamGrassID).setUnlocalizedName("dreamgrass").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block fireCrystal = new ModBlock(b.firecrystalID).registerTexture("FireCrystal").setLightValue(0.7F).setUnlocalizedName("firecrystal").setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Blocks);

	public static final Block dreamwood = new ModLog(b.dreamwoodID, "DreamWood").setUnlocalizedName("dreamwood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreamwoodLeaves = new ModLeaves(b.dreamwoodLeavesID, "DreamWood").setUnlocalizedName("dreamwoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreambricks = new BlockVethea(b.dreambricksID, Material.rock).registerTexture("DreamBricks1").setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block lunastone = new BlockVethea(b.lunastoneID, Material.rock).registerTexture("LunaStone").setBlockUnbreakable().setUnlocalizedName("lunastone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block lunabricks = new BlockVethea(b.lunabricksID, Material.rock).registerTexture("LunaBrick").setBlockUnbreakable().setUnlocalizedName("lunabricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block metalCaging = new BlockVethea(b.metalCagingID, Material.rock).registerTexture("MetalCaging").setUnlocalizedName("metalCaging").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreamlampOn = new BlockDreamLamp(b.dreamlampOnID, 30, Material.glass, true).registerTexture("DreamLamp_On").setBlockUnbreakable().setUnlocalizedName("dreamlampOn").setHardness(1F).setResistance(1F).setLightValue(1.0F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreamlamp = new BlockDreamLamp(b.dreamlampID, 31, Material.glass, false).registerTexture("DreamLamp_Off").setBlockUnbreakable().setUnlocalizedName("dreamlamp").setHardness(1F).setStepSound(Block.soundGlassFootstep).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block weedwoodVine = new BlockAzuriteVine(b.weedwoodVineID, "WeedWood").setUnlocalizedName("weedwoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block blossomingWeedwoodVine = new BlockAzuriteVine(b.blossomingWeedwoodVineID, "WeedWoodBlossomed").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block cryptWall = new BlockVethea(b.cryptWallID, Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("cryptWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block smoothGlass = new ModGlass(b.smoothGlassID).registerTexture("SmoothGlass").setStepSound(Block.soundGlassFootstep).setUnlocalizedName("smoothGlass").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block villageLamp = new BlockVethea(b.villageLampID, Material.glass).registerTexture("VillageLamp").setUnlocalizedName("villageLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block cellLamp = new BlockVethea(b.cellLampID, Material.glass).registerTexture("CellLamp").setUnlocalizedName("cellLamp").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block barredDoor = new BlockBarredDoor(b.barredDoorID, Material.wood, "BarredDoor").setUnlocalizedName("barredDoor").setHardness(1F).setResistance(1F).setCreativeTab(null);
	public static final Block firelight = new BlockVethea(b.firelightID, Material.glass).registerTexture("FireLight").setUnlocalizedName("firelight").setLightValue(1.0F).setStepSound(Block.soundGlassFootstep).setHardness(1F).setResistance(1.0F).setCreativeTab(DivineRPG.Blocks);
	public static final Block hyrewood = new ModLog(b.hyrewoodID, "HyreWood").setUnlocalizedName("hyrewood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block mintwoodLeaves = new ModLeaves(b.mintwoodLeavesID, "MintWood").setUnlocalizedName("mintwoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block firewall = new BlockVethea(b.firewallID, Material.rock).registerTexture("FireWall").setUnlocalizedName("firewall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block karosHeatTileGreen = new BlockKarosHeatTileGreen(b.karosHeatTileGreenID, false).registerTexture("KarosHeatTile1").setBlockUnbreakable().setUnlocalizedName("karosHeatTileGreen").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block karosHeatTileRed = new BlockKarosHeatTileRed(b.karosHeatTileRedID, true).registerTexture("KarosHeatTile2").setBlockUnbreakable().setUnlocalizedName("karosHeatTileRed").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block firewood = new ModLog(b.firewoodID, "FireWood").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block bacterialAcid = new BlockBacterialAcid(b.bacterialAcidID).registerTexture("VetheaPortal").setUnlocalizedName("bacterialAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block blockAcid = new BlockAcid(b.blockAcidID).registerTexture("VetheaPortal").setUnlocalizedName("blockAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block everstone = new BlockVethea(b.everstoneID, Material.rock).registerTexture("GreenEverstone").setBlockUnbreakable().setUnlocalizedName("everstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block lunicAcid = new BlockLunicAcid(b.lunicAcidID, 141).registerTexture("VetheaPortal").setUnlocalizedName("lunicAcid").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block firewoodLeaves = new ModLeaves(b.firewoodLeavesID, "FireWood").setUnlocalizedName("firewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block hyrewoodLeaves = new ModLeaves(b.hyrewoodLeavesID, "HyreWood").setUnlocalizedName("hyrewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block gemtopGreen = new BlockVetheaPlant(b.gemtopGreenID).registerTexture("GreenGemTop").setUnlocalizedName("gemtopGreen").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block gemtopPurple = new BlockVetheaPlant(b.gemtopPurpleID).registerTexture("PurpleGemTop").setUnlocalizedName("gemtopPurple").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block yellowDulah = new BlockVetheaPlant(b.yellowDulahID).registerTexture("YellowDulah").setUnlocalizedName("yellowDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block greenDulah = new BlockVetheaPlant(b.greenDulahID).registerTexture("GreenDulah").setUnlocalizedName("greenDulah").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block mintwood = new ModLog(b.mintwoodID, "MintWood").setUnlocalizedName("mint").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block lightFirewoodLeaves = new ModLeaves(b.lightFirewoodLeavesID, "FireWood").setUnlocalizedName("lightFirewoodLeaves").setHardness(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block cracklespike = new BlockVetheaPlant(b.cracklespikeID).registerTexture("CrackleSpike").setUnlocalizedName("cracklespike").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block fernite = new BlockVetheaPlant(b.ferniteID).registerTexture("Fernite").setUnlocalizedName("Fernite").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block bulatobe = new BlockVetheaPlant(b.bulatobeID).registerTexture("Bulbatobe").setUnlocalizedName("Bulbatobe").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block shineGrass = new BlockVetheaPlant(b.shineGrassID).registerTexture("ShineGrass").setUnlocalizedName("ShineGrass").setLightValue(0.4F).setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	//public static final Block shimmer = new BlockShimmer(b.shimmerID).setLightValue(0.4F).setUnlocalizedName("shimmer").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block hiveWall = new BlockVethea(b.hiveWallID, Material.glass).registerTexture("HiveWalls").setLightValue(0.533F).setUnlocalizedName("dreamlampOn").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	//public static final Block dreamglow = new BlockShimmer(b.dreamglowID).setLightValue(0.4F).setUnlocalizedName("dreamglow").setHardness(0.0F).setStepSound(Block.soundGrassFootstep).setCreativeTab(DivineRPG.Blocks);
	public static final Block hyrewoodVine = new BlockAzuriteVine(b.hyrewoodVineID, "WeedWood").setUnlocalizedName("hyrewoodVine").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block dreambricks2 = new BlockVethea(b.dreambricks2ID, Material.rock).registerTexture("DreamBricks2").setUnlocalizedName("dreambricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block chamberWall = new BlockVethea(b.chamberWallID, Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("chamberWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block chamberWall1 = new BlockVethea(b.chamberWall1ID, Material.rock).registerTexture("ChamberWall2").setBlockUnbreakable().setUnlocalizedName("chamberWall1").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block chamberWall2 = new BlockVethea(b.chamberWall2ID, Material.rock).registerTexture("ChamberWall3").setBlockUnbreakable().setUnlocalizedName("chamberWall2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block whiteEverstone = new BlockVethea(b.whiteEverstoneID, Material.rock).registerTexture("WhiteEverstone").setBlockUnbreakable().setUnlocalizedName("whiteEverstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block darkEverstone = new BlockVethea(b.darkEverstoneID, Material.rock).registerTexture("DarkEverstone").setBlockUnbreakable().setUnlocalizedName("darkEverstone").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block infusionTable = new BlockInfusionTable(b.infusionTableID).setBlockUnbreakable().setUnlocalizedName("infusionTable").setBlockUnbreakable().setResistance(999F).setCreativeTab(DivineRPG.Blocks);
	public static final Block hungerstone1 = new BlockVethea(b.hungerstone1ID, Material.rock).registerTexture("HungerStone1").setUnlocalizedName("hungerstone1").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block hungerstone2 = new BlockVethea(b.hungerstone2ID, Material.rock).registerTexture("HungerStone2").setUnlocalizedName("hungerstone2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block cryptFloor = new BlockVethea(b.cryptFloorID, Material.rock).registerTexture("CryptFloor").setBlockUnbreakable().setUnlocalizedName("cryptFloor").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block hallWall = new BlockVethea(b.hallWallID, Material.rock).registerTexture("ChamberWall1").setBlockUnbreakable().setUnlocalizedName("hallWall").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block karosBricks = new BlockVethea(b.karosBricksID, Material.rock).registerTexture("KarosBrick").setBlockUnbreakable().setUnlocalizedName("karosBricks").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block karosBricks2 = new BlockVethea(b.karosBricks2ID, Material.rock).registerTexture("KarosBrick").setBlockUnbreakable().setUnlocalizedName("karosBricks2").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final BlockHelioticBeam helioticBeam = (BlockHelioticBeam) new BlockHelioticBeam(b.helioticBeamID).registerTexture("HelioticBeam_Side", "HelioticBeam_Top", "HelioticBeam_Top").setUnlocalizedName("helioticBeam").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final BlockKarosCannon karosCannon = (BlockKarosCannon) new BlockKarosCannon(b.karosCannonID, Material.rock).registerTexture("KarosCannon").setBlockUnbreakable().setUnlocalizedName("karosCannon").setHardness(1F).setResistance(1F).setCreativeTab(DivineRPG.Blocks);
	public static final Block purpleFire = new BlockPurpleFire(b.purpleFireID).setUnlocalizedName("purpleFire");


	public static void addNames() {
		addBlock(gorgosionSpawner, "Gorgosion Spawner");
		addBlock(biphronSpawner, "Biphron Spawner");
		addBlock(twinsSpawner, "Twins Spawner");
		addBlock(dreamwreckerSpawner, "Dreamwrecker Spawner");
		addBlock(vermenousSpawner, "Vermenous Spawner");
		addBlock(vetheaPortal, "Vethea Portal");
		addBlock(dreamStone, "Dreamstone");
		addBlock(dreamGrass, "Dream Grass");
		addBlock(dreamDirt, "Dream Dirt");
		addBlock(dreamwood, "Dreamwood");
		addBlock(dreamwoodLeaves, "Dreamwood Leaves");
		addBlock(dreambricks, "Dreambricks");
		addBlock(dreambricks2, "Dreambricks");
		addBlock(lunastone, "Lunastone");
		addBlock(metalCaging, "Metal Caging");
		addBlock(weedwoodVine, "Weedwood Vines");
		addBlock(blossomingWeedwoodVine, "Blossoming Weedwood Vines");
		addBlock(cryptWall, "Crypt Wall");
		addBlock(smoothGlass, "Smooth Glass");
		addBlock(villageLamp, "Altar Lamps");
		addBlock(infusionTable, "Infusion Table");
		addBlock(cellLamp, "Cell Lamp");
		addBlock(barredDoor, "Barred Door");
		addBlock(fireCrystal, "Firecrystal");
		addBlock(firelight, "Firelight");
		addBlock(hyrewood, "Hyrewood");
		addBlock(mintwoodLeaves, "Mintwood Leaves");
		addBlock(firewall, "Firewall");
		addBlock(karosHeatTileGreen, "Karos Heat Tile");
		addBlock(karosHeatTileRed, "Karos Heat Tile");
		addBlock(karosCannon, "Karos Cannon");
		addBlock(helioticBeam, "Heliotic Beam");
		addBlock(cryptFloor, "Crypt Floor");
		addBlock(firewood, "Firewood");
		addBlock(chamberWall, "Chamber Wall");
		addBlock(chamberWall1, "Chamber Wall");
		addBlock(chamberWall2, "Chamber Wall");
		addBlock(karosBricks, "Karos Bricks");
		addBlock(karosBricks2, "Karos Bricks");
		addBlock(bacterialAcid, "Bacterial Acid");
		addBlock(hungerstone1, "Hungerstone");
		addBlock(hungerstone2, "Hungerstone");
		addBlock(blockAcid, "Acid");
		addBlock(hallWall, "Hall Wall");
		addBlock(wreckAltar, "Wreck Altar");
		addBlock(raglokAltar, "Raglok Altar");
		addBlock(karosAltar, "Karos Altar");
		addBlock(lunicAltar, "Lunic Altar");
		addBlock(quadroticAltar, "Quadrotic Altar");
		addBlock(hiveWall, "Hive Walls");
		addBlock(darkEverstone, "Dark Everstone");
		addBlock(whiteEverstone, "White Everstone");
		addBlock(everstone, "Everstone");
		addBlock(lunicAcid, "Lunic Acid");
		addBlock(firewoodLeaves, "Firewood Leaves");
		addBlock(hyrewoodLeaves, "Hyrewood Leaves");
		addBlock(gemtopGreen, "Green Gemtops");
		addBlock(gemtopPurple, "Purple Gemtops");
		addBlock(yellowDulah, "Yellow Dulahs");
		addBlock(greenDulah, "Green Dulahs");
		addBlock(mintwood, "Mintwood");
		addBlock(lightFirewoodLeaves, "Light Firewood Leaves");
		addBlock(cracklespike, "Crackle Spikes");
		addBlock(fernite, "Fernites");
		addBlock(bulatobe, "Bulbatobes");
		addBlock(shineGrass, "Shine Grass");
		//addBlock(shimmer, "Shimmers");
		//addBlock(dreamglow, "Dream Glows");
		addBlock(hyrewoodVine, "Hyrewood Vines");
	}

}
