package net.divinerpg.helper;

import net.divinerpg.block.model.RenderStatue;
import net.divinerpg.block.model.RenderStatueItem;
import net.divinerpg.client.render.model.*;
import net.divinerpg.helper.block.ArcanaBlockHelper;
import net.divinerpg.helper.block.OverworldBlockHelper;
import net.divinerpg.helper.item.*;
import net.divinerpg.lib.*;
import net.divinerpg.mob.entity.*;
import net.divinerpg.mob.entity.item.*;
import net.divinerpg.overworld.block.tileentity.TileEntityStatue;
import net.divinerpg.overworld.mobs.EntityAncient;
import net.divinerpg.overworld.mobs.EntityAyeracoBlue;
import net.divinerpg.overworld.mobs.EntityAyeracoGreen;
import net.divinerpg.overworld.mobs.EntityAyeracoPurple;
import net.divinerpg.overworld.mobs.EntityAyeracoRed;
import net.divinerpg.overworld.mobs.EntityAyeracoYellow;
import net.divinerpg.overworld.mobs.EntityCaveCrawler;
import net.divinerpg.overworld.mobs.EntityCaveclops;
import net.divinerpg.overworld.mobs.EntityCrab;
import net.divinerpg.overworld.mobs.EntityCyclops;
import net.divinerpg.overworld.mobs.EntityDesertCrawler;
import net.divinerpg.overworld.mobs.EntityEnderSpider;
import net.divinerpg.overworld.mobs.EntityEnderTriplets;
import net.divinerpg.overworld.mobs.EntityEnderWatcher;
import net.divinerpg.overworld.mobs.EntityEnthralledDramcryx;
import net.divinerpg.overworld.mobs.EntityFrost;
import net.divinerpg.overworld.mobs.EntityHellBat;
import net.divinerpg.overworld.mobs.EntityHellPig;
import net.divinerpg.overworld.mobs.EntityHellSpider;
import net.divinerpg.overworld.mobs.EntityIceMan;
import net.divinerpg.overworld.mobs.EntityJackOMan;
import net.divinerpg.overworld.mobs.EntityJungleBat;
import net.divinerpg.overworld.mobs.EntityJungleDramcryx;
import net.divinerpg.overworld.mobs.EntityJungleSpider;
import net.divinerpg.overworld.mobs.EntityKingCrab;
import net.divinerpg.overworld.mobs.EntityKingOfScorchers;
import net.divinerpg.overworld.mobs.EntityMiner;
import net.divinerpg.overworld.mobs.EntityNetherWatcher;
import net.divinerpg.overworld.mobs.EntityRainbour;
import net.divinerpg.overworld.mobs.EntityRotatick;
import net.divinerpg.overworld.mobs.EntityScorcher;
import net.divinerpg.overworld.mobs.EntityShark;
import net.divinerpg.overworld.mobs.EntityTheEye;
import net.divinerpg.overworld.mobs.EntityWhale;
import net.divinerpg.overworld.mobs.EntityWildFire;
import net.divinerpg.render.entity.*;
import net.divinerpg.render.entity.overworld.*;
import net.divinerpg.twilight.mobs.EntityAridWarrior;
import net.minecraft.client.model.*;
import net.minecraft.client.renderer.entity.*;
import net.minecraft.item.Item;
import net.minecraftforge.client.MinecraftForgeClient;
import cpw.mods.fml.client.registry.ClientRegistry;
import cpw.mods.fml.client.registry.RenderingRegistry;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class OverworldMobRendering 
{
	public static EntityResourceLocs x;
	
	public static void init()
	{
		RenderingRegistry.registerEntityRenderingHandler(EntityShuriken.class, new RenderTeakerDisc(OverworldItemHelper.shuriken));
        RenderingRegistry.registerEntityRenderingHandler(EntityVailStorm.class, new RenderTeakerDisc(OverworldItemHelper.vileStorm));
        RenderingRegistry.registerEntityRenderingHandler(EntityFireArrow.class, new RenderBasicArrow(x.FIRE_ARROW));
        RenderingRegistry.registerEntityRenderingHandler(EntityExplosiveArrow.class, new RenderBasicArrow(x.BLUEFIRE_ARROW));
        RenderingRegistry.registerEntityRenderingHandler(EntityStromBall.class, new RenderBasicProjectile(x.STROM_BALL));
        RenderingRegistry.registerEntityRenderingHandler(EntityMusicBall.class, new RenderBasicProjectile(x.MUSIC));
        RenderingRegistry.registerEntityRenderingHandler(EntityGhastTear.class, new RenderBasicProjectile(x.GHAST_TEAR));
        RenderingRegistry.registerEntityRenderingHandler(EntityFrostShard.class, new RenderBasicProjectile(x.FROST_SHARD));
        RenderingRegistry.registerEntityRenderingHandler(EntityDeathSeranade.class, new RenderBasicProjectile(x.DEATH_SERENADE));
        RenderingRegistry.registerEntityRenderingHandler(EntityTripletProjectile.class, new RenderTripletShot(x.ENDER_TRIPLET_PROJECTILE, 1.5F));
        RenderingRegistry.registerEntityRenderingHandler(EntityCaveRock.class, new RenderBasicProjectile(x.CAVE_ROCK));
        RenderingRegistry.registerEntityRenderingHandler(EntityCrabCannon.class, new RenderBasicProjectile(x.CRAB_CANNON));
        RenderingRegistry.registerEntityRenderingHandler(EntityBowCannon.class, new RenderSnowball(Item.snowball));
        RenderingRegistry.registerEntityRenderingHandler(EntityAnchor.class, new RenderBasicProjectile(x.ANCHOR));
        RenderingRegistry.registerEntityRenderingHandler(EntityEnderArrow.class, new RenderBasicArrow(x.ENDER_ARROW));
        RenderingRegistry.registerEntityRenderingHandler(EntityCorruptShot.class, new RenderBasicProjectile(x.CORRUPT_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityMamormeterShot.class, new RenderKingShot(x.KING_OF_SCORCHERS_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityCyclopsianStaff.class, new RenderBasicProjectile(x.CYCLOPSE_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityBatWing.class, new RenderBasicProjectile(x.SCYTHE));
        RenderingRegistry.registerEntityRenderingHandler(EntityWatcherShot.class, new RenderBasicProjectile(x.WATCHER_SHOT)); 
        RenderingRegistry.registerEntityRenderingHandler(EntityBlueFireBall.class, new RenderTripletShot(x.ENDER_TRIPLET_PROJECTILE, 1.5F)); 

        RenderingRegistry.registerEntityRenderingHandler(EntityMiner.class, new RenderUndeadMiner(new ModelZombie(), 0.0F, x.MINER));
        RenderingRegistry.registerEntityRenderingHandler(EntityFrost.class, new RenderDivineMob(new ModelFrost(), 0.0F, x.FROST));
        RenderingRegistry.registerEntityRenderingHandler(EntityJungleSpider.class, new RenderDivineMob(new ModelJungleSpider(), 0.0F, x.JUNGLE_SPIDER));
        RenderingRegistry.registerEntityRenderingHandler(EntityScorcher.class, new RenderSizeable(new ModelScorcher(), 0.0F, 2.0F, x.SCORCHER));
        RenderingRegistry.registerEntityRenderingHandler(EntityHellSpider.class, new RenderDivineMob(new ModelHellSpider(), 0.0F, x.HELL_SPIDER));
        RenderingRegistry.registerEntityRenderingHandler(EntityNetherWatcher.class, new RenderNetherWatcher(new ModelWatcher(), 0.0F, 5.0F, x.WATCHER));
        RenderingRegistry.registerEntityRenderingHandler(EntityCyclops.class, new RenderSizeable(new ModelBiped(), 0.0F, 2.0F, x.CYCLOPS));
        RenderingRegistry.registerEntityRenderingHandler(EntityEnderWatcher.class, new RenderDivineMob(new ModelWatcher(), 0.0F, x.ENDER_WATCHER));
        RenderingRegistry.registerEntityRenderingHandler(EntityKingOfScorchers.class, new RenderMamormeter(new ModelMamormeter(), 1.0F, 2, EntityResourceLocs.KING_OF_SCHORCHERS));
        RenderingRegistry.registerEntityRenderingHandler(EntityCrab.class, new RenderDivineMob(new ModelCrab(), 0.0F, x.CRAB));
        RenderingRegistry.registerEntityRenderingHandler(EntityShark.class, new RenderDivineMob(new ModelShark(), 0.0F, x.SHARK));
        RenderingRegistry.registerEntityRenderingHandler(EntityWhale.class, new RenderSizeable(new ModelWhale(), 0.0F, 3.0F, x.WHALE));
        RenderingRegistry.registerEntityRenderingHandler(EntityKingCrab.class, new RenderSizeable(new ModelCrab(), 0.0F, 1.9F, x.CRAB));
        RenderingRegistry.registerEntityRenderingHandler(EntityIceMan.class, new RenderDivineMob(new ModelBiped(), 0.0F, x.ICE_MAN));
        RenderingRegistry.registerEntityRenderingHandler(EntityJackOMan.class, new RenderJackOMan(new ModelBiped(), 0, x.JACK_O_MAN));
        RenderingRegistry.registerEntityRenderingHandler(EntityCaveCrawler.class, new RenderDivineMob(new ModelCrawler(), 0.0F, x.CAVE_CRAWLER));
        RenderingRegistry.registerEntityRenderingHandler(EntityAridWarrior.class, new RenderDivineMob(new ModelAridWarrior(), 0.0F, x.ARID_WARRIOR));
        RenderingRegistry.registerEntityRenderingHandler(EntityJungleDramcryx.class, new RenderDivineMob(new ModelDramcryx(), 0.0F, x.DRAMCRYX));
        RenderingRegistry.registerEntityRenderingHandler(EntityEnthralledDramcryx.class, new RenderSizeable(new ModelDramcryx(), 1.0F, 1.5F, x.ENTHRALLED_DRAMCRYX));
        RenderingRegistry.registerEntityRenderingHandler(EntityTheEye.class, new RenderDivineMob(new ModelEye(), 0.0F, x.THE_EYE));
        RenderingRegistry.registerEntityRenderingHandler(EntityDesertCrawler.class, new RenderDivineMob(new ModelCrawler(), 0.0F, x.DESERT_CRAWLER));
        RenderingRegistry.registerEntityRenderingHandler(EntityRotatick.class, new RenderDivineMob(new ModelRotatick(), 0.0F, x.ROTATICK));
        RenderingRegistry.registerEntityRenderingHandler(EntityJungleBat.class, new RenderDivineMob(new ModelJungleBat(), 0.0F, x.JUNGLE_BAT));
        RenderingRegistry.registerEntityRenderingHandler(EntityEnderTriplets.class, new RenderDivineMob(new ModelEnderTriplets(), 1.5F, x.ENDER_TRIPLETS));
        RenderingRegistry.registerEntityRenderingHandler(EntityCaveclops.class, new RenderSizeable(new ModelBiped(), 0.0F, 2.0F, x.CAVE_CLOPS));
        RenderingRegistry.registerEntityRenderingHandler(EntityRainbour.class, new RenderDivineMob(new ModelRainbour(), 0.0F, x.RAINBOUR));
        RenderingRegistry.registerEntityRenderingHandler(EntityEnderSpider.class, new RenderSizeable(new ModelSpider(), 0.5F, 0.5F, x.ENDER_SPIDER));
        RenderingRegistry.registerEntityRenderingHandler(EntityAyeracoYellow.class, new RenderAyeraco(new ModelAyeraco(), 0.0F, 3.0F, x.AYERACO_YELLOW));
        RenderingRegistry.registerEntityRenderingHandler(EntityAyeracoGreen.class, new RenderAyeraco(new ModelAyeraco(), 0.0F, 3.0F, x.AYERACO_GREEN));
        RenderingRegistry.registerEntityRenderingHandler(EntityAyeracoBlue.class, new RenderAyeraco(new ModelAyeraco(), 0.0F, 3.0F, x.AYERACO_BLUE));
        RenderingRegistry.registerEntityRenderingHandler(EntityAyeracoRed.class, new RenderAyeraco(new ModelAyeraco(), 0.0F, 3.0F, x.AYERACO_RED));
        RenderingRegistry.registerEntityRenderingHandler(EntityAyeracoPurple.class, new RenderAyeraco(new ModelAyeraco(), 0.0F, 3.0F, x.AYERACO_PURPLE));
        RenderingRegistry.registerEntityRenderingHandler(EntityWildFire.class, new RenderWildFire(new ModelWildFire(), 0.0F, 3.0F, x.WILDFIRE));
        RenderingRegistry.registerEntityRenderingHandler(EntityHellPig.class, new RenderDivineMob(new ModelPig(), 0.0F, x.HELL_PIG));
        RenderingRegistry.registerEntityRenderingHandler(EntityAncient.class, new RenderAncient(new ModelAncientEntity(), 3.0F, 3.0F, x.ANCIENT_ENTITY));
        RenderingRegistry.registerEntityRenderingHandler(EntityHellBat.class, new RenderDivineMob(new ModelHellBat(), 0.0F, x.HELL_BAT));
	
        MinecraftForgeClient.registerItemRenderer(OverworldBlockHelper.KingStatue.blockID, new RenderStatueItem(OverworldBlockHelper.KingStatue));
        MinecraftForgeClient.registerItemRenderer(OverworldBlockHelper.AncientStatue.blockID, new RenderStatueItem(OverworldBlockHelper.AncientStatue));
        MinecraftForgeClient.registerItemRenderer(OverworldBlockHelper.AyeracoStatue.blockID, new RenderStatueItem(OverworldBlockHelper.AyeracoStatue));
        MinecraftForgeClient.registerItemRenderer(OverworldBlockHelper.TwilightDemonStatue.blockID, new RenderStatueItem(OverworldBlockHelper.TwilightDemonStatue));
        MinecraftForgeClient.registerItemRenderer(OverworldBlockHelper.VamacheronStatue.blockID, new RenderStatueItem(OverworldBlockHelper.VamacheronStatue));
        MinecraftForgeClient.registerItemRenderer(OverworldBlockHelper.DensosStatue.blockID, new RenderStatueItem(OverworldBlockHelper.DensosStatue));
        MinecraftForgeClient.registerItemRenderer(OverworldBlockHelper.DexStatue.blockID, new RenderStatueItem(OverworldBlockHelper.DexStatue));
        MinecraftForgeClient.registerItemRenderer(OverworldBlockHelper.DramixStatue.blockID, new RenderStatueItem(OverworldBlockHelper.DramixStatue));
        MinecraftForgeClient.registerItemRenderer(OverworldBlockHelper.ParasectaStatue.blockID, new RenderStatueItem(OverworldBlockHelper.ParasectaStatue));
        MinecraftForgeClient.registerItemRenderer(OverworldBlockHelper.SoulFiendStatue.blockID, new RenderStatueItem(OverworldBlockHelper.SoulFiendStatue));
        MinecraftForgeClient.registerItemRenderer(OverworldBlockHelper.WatcherStatue.blockID, new RenderStatueItem(OverworldBlockHelper.WatcherStatue));
        ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStatue.class, new RenderStatue());
	}
}
