package net.divinerpg.helper;

import net.divinerpg.arcana.mobs.EntityVermsillion;
import net.divinerpg.client.render.RenderBasicArrow;
import net.divinerpg.helper.item.VetheaItemHelper;
import net.divinerpg.lib.EntityResourceLocs;
import net.divinerpg.mob.entity.item.EntityAmthirmisDisk;
import net.divinerpg.mob.entity.item.EntityArksianeDisk;
import net.divinerpg.mob.entity.item.EntityBouncingProjectile;
import net.divinerpg.mob.entity.item.EntityCermileDisk;
import net.divinerpg.mob.entity.item.EntityDarvenDisk;
import net.divinerpg.mob.entity.item.EntityDissimentShot;
import net.divinerpg.mob.entity.item.EntityEvernightProjectile;
import net.divinerpg.mob.entity.item.EntityEversightProjectile;
import net.divinerpg.mob.entity.item.EntityHeliosisDisk;
import net.divinerpg.mob.entity.item.EntityKarosCannonShot;
import net.divinerpg.mob.entity.item.EntityKarosDisk;
import net.divinerpg.mob.entity.item.EntityKazroticShot;
import net.divinerpg.mob.entity.item.EntityPardimalDisk;
import net.divinerpg.mob.entity.item.EntityQuadroticDisk;
import net.divinerpg.mob.entity.item.EntityRaglokBomb;
import net.divinerpg.mob.entity.item.EntitySpinebackDisc;
import net.divinerpg.mob.entity.item.EntityTeakerDisk;
import net.divinerpg.mob.entity.item.EntityVetheanArrow;
import net.divinerpg.mob.entity.item.EntityVetheanArrow2;
import net.divinerpg.mob.entity.item.EntityVetheanCannonShot;
import net.divinerpg.mob.entity.item.EntityVetheanWarArrow;
import net.divinerpg.mob.entity.item.EntityVetheanWrathArrow;
import net.divinerpg.mob.entity.item.EntityWreckExplosiveShot;
import net.divinerpg.mob.entity.item.EntityWreckStrengthShot;
import net.divinerpg.mob.entity.item.EntityZoragonBomb;
import net.divinerpg.render.entity.RenderBasicProjectile;
import net.divinerpg.render.entity.RenderTeakerDisc;
import net.divinerpg.render.entity.model.AcidHag;
import net.divinerpg.render.entity.model.Biphron;
import net.divinerpg.render.entity.model.Boheimite;
import net.divinerpg.render.entity.model.CryptKeeper;
import net.divinerpg.render.entity.model.Cymesoid;
import net.divinerpg.render.entity.model.Dissiment;
import net.divinerpg.render.entity.model.Dreamwrecker;
import net.divinerpg.render.entity.model.Ehu;
import net.divinerpg.render.entity.model.Endiku;
import net.divinerpg.render.entity.model.Ent;
import net.divinerpg.render.entity.model.Galroid;
import net.divinerpg.render.entity.model.Gorgosion;
import net.divinerpg.render.entity.model.Helio;
import net.divinerpg.render.entity.model.Herbomancer;
import net.divinerpg.render.entity.model.HiveQueen;
import net.divinerpg.render.entity.model.HiveSoldier;
import net.divinerpg.render.entity.model.HoverStinger;
import net.divinerpg.render.entity.model.Husk;
import net.divinerpg.render.entity.model.Karos;
import net.divinerpg.render.entity.model.Kazrotic;
import net.divinerpg.render.entity.model.LadyLuna;
import net.divinerpg.render.entity.model.Lheiva;
import net.divinerpg.render.entity.model.Lorga;
import net.divinerpg.render.entity.model.Lorgaflight;
import net.divinerpg.render.entity.model.Mandragora;
import net.divinerpg.render.entity.model.ModelHungerHungry;
import net.divinerpg.render.entity.model.MysteriousMan;
import net.divinerpg.render.entity.model.RaglokGogdure;
import net.divinerpg.render.entity.model.Shadahier;
import net.divinerpg.render.entity.model.SpinebackBody;
import net.divinerpg.render.entity.model.SpinebackHead;
import net.divinerpg.render.entity.model.StoneGolem;
import net.divinerpg.render.entity.model.Tocaxin;
import net.divinerpg.render.entity.model.Vermenous;
import net.divinerpg.render.entity.model.Versmillion;
import net.divinerpg.render.entity.model.Vhraak;
import net.divinerpg.render.entity.model.WreckForm1;
import net.divinerpg.render.entity.model.Zone;
import net.divinerpg.render.entity.model.Zoragon;
import net.divinerpg.render.entity.overworld.RenderDivineMob;
import net.divinerpg.twilight.mobs.EntitySpinebackWorm;
import net.divinerpg.twilight.mobs.EntitySpinebackWormBody;
import net.divinerpg.vethea.entity.EntityAcidHag;
import net.divinerpg.vethea.entity.EntityBiphron;
import net.divinerpg.vethea.entity.EntityBohemite;
import net.divinerpg.vethea.entity.EntityCryptKeeper;
import net.divinerpg.vethea.entity.EntityCymesoid;
import net.divinerpg.vethea.entity.EntityDissiment;
import net.divinerpg.vethea.entity.EntityDreamwrecker;
import net.divinerpg.vethea.entity.EntityDuo;
import net.divinerpg.vethea.entity.EntityEhu;
import net.divinerpg.vethea.entity.EntityEndiku;
import net.divinerpg.vethea.entity.EntityEnt;
import net.divinerpg.vethea.entity.EntityGalroid;
import net.divinerpg.vethea.entity.EntityGorgosion;
import net.divinerpg.vethea.entity.EntityHelio;
import net.divinerpg.vethea.entity.EntityHerbomancer;
import net.divinerpg.vethea.entity.EntityHiveQueen;
import net.divinerpg.vethea.entity.EntityHiveSoldier;
import net.divinerpg.vethea.entity.EntityHoverStinger;
import net.divinerpg.vethea.entity.EntityHungerHungry;
import net.divinerpg.vethea.entity.EntityHusk;
import net.divinerpg.vethea.entity.EntityKaros;
import net.divinerpg.vethea.entity.EntityKazrotic;
import net.divinerpg.vethea.entity.EntityLadyLuna;
import net.divinerpg.vethea.entity.EntityLheiva;
import net.divinerpg.vethea.entity.EntityLorga;
import net.divinerpg.vethea.entity.EntityLorgaFlight;
import net.divinerpg.vethea.entity.EntityMandragora;
import net.divinerpg.vethea.entity.EntityMysteriousManLayer1;
import net.divinerpg.vethea.entity.EntityMysteriousManLayer2;
import net.divinerpg.vethea.entity.EntityMysteriousManLayer3;
import net.divinerpg.vethea.entity.EntityQuadro;
import net.divinerpg.vethea.entity.EntityRaglok;
import net.divinerpg.vethea.entity.EntityShadahier;
import net.divinerpg.vethea.entity.EntityStoneGolem;
import net.divinerpg.vethea.entity.EntityTempleGuardian;
import net.divinerpg.vethea.entity.EntityTocaxin;
import net.divinerpg.vethea.entity.EntityTwins;
import net.divinerpg.vethea.entity.EntityVermenous;
import net.divinerpg.vethea.entity.EntityVhraak;
import net.divinerpg.vethea.entity.EntityWreck;
import net.divinerpg.vethea.entity.EntityZone;
import net.divinerpg.vethea.entity.EntityZoragon;
import net.divinerpg.vethea.entity.item.EntityMandragoraProjectile;
import net.divinerpg.vethea.entity.render.RenderBiphron;
import net.divinerpg.vethea.entity.render.RenderGalroid;
import net.divinerpg.vethea.entity.render.RenderHiveQueen;
import net.divinerpg.vethea.entity.render.RenderWreck;
import net.divinerpg.vethea.entity.render.model.Duo;
import net.divinerpg.vethea.entity.render.model.Quadro;
import net.divinerpg.vethea.entity.render.model.Twins;
import net.minecraft.client.model.ModelBiped;
import cpw.mods.fml.client.registry.RenderingRegistry;



public class VetheaMobRendering {

	public static EntityResourceLocs x;
	
	public static void init()
    {
        RenderingRegistry.registerEntityRenderingHandler(EntityVermenous.class, new RenderDivineMob(new Vermenous(), 0.0F, x.VERMENOUS));
        RenderingRegistry.registerEntityRenderingHandler(EntityEnt.class, new RenderDivineMob(new Ent(), 0.0F, x.ENT));
        RenderingRegistry.registerEntityRenderingHandler(EntityCymesoid.class, new RenderDivineMob(new Cymesoid(), 0.0F, x.CYMESOID));
        RenderingRegistry.registerEntityRenderingHandler(EntityDreamwrecker.class, new RenderDivineMob(new Dreamwrecker(), 0.0F, x.DREAMWRECKER));
        RenderingRegistry.registerEntityRenderingHandler(EntityTocaxin.class, new RenderDivineMob(new Tocaxin(), 0.0F, x.TOCAXIN));
        RenderingRegistry.registerEntityRenderingHandler(EntityShadahier.class, new RenderDivineMob(new Shadahier(), 0.0F, x.SHADAHIER));
        RenderingRegistry.registerEntityRenderingHandler(EntityAcidHag.class, new RenderDivineMob(new AcidHag(), 0.0F, x.ACID_HAG));
        RenderingRegistry.registerEntityRenderingHandler(EntityKazrotic.class, new RenderDivineMob(new Kazrotic(), 0.0F, x.KAZROTIC));
        RenderingRegistry.registerEntityRenderingHandler(EntityHelio.class, new RenderDivineMob(new Helio(), 0.0F, x.HELIO));
        RenderingRegistry.registerEntityRenderingHandler(EntityGorgosion.class, new RenderDivineMob(new Gorgosion(), 0.0F, x.GORGOSION));
        RenderingRegistry.registerEntityRenderingHandler(EntityHoverStinger.class, new RenderDivineMob(new HoverStinger(), 0.0F, x.HOVER_STINGER));
        RenderingRegistry.registerEntityRenderingHandler(EntityZone.class, new RenderDivineMob(new Zone(), 0.0F, x.ZONE));
        RenderingRegistry.registerEntityRenderingHandler(EntityZoragon.class, new RenderDivineMob(new Zoragon(), 0.0F, x.ZORAGON));
        RenderingRegistry.registerEntityRenderingHandler(EntityDissiment.class, new RenderDivineMob(new Dissiment(), 0.0F, x.DISSIMENT));
        RenderingRegistry.registerEntityRenderingHandler(EntitySpinebackWorm.class, new RenderDivineMob(new SpinebackBody(), 0.0F, x.ALICANTO));
        RenderingRegistry.registerEntityRenderingHandler(EntitySpinebackWormBody.class, new RenderDivineMob(new SpinebackHead(), 0.0F, x.VAMACHERON));
        RenderingRegistry.registerEntityRenderingHandler(EntityVhraak.class, new RenderDivineMob(new Vhraak(), 0.0F, x.VHRAAK));
        RenderingRegistry.registerEntityRenderingHandler(EntityGalroid.class, new RenderGalroid(new Galroid(), 0.0F, x.GALROID));
        RenderingRegistry.registerEntityRenderingHandler(EntityLadyLuna.class, new RenderDivineMob(new LadyLuna(), 0.0F, x.LADY_LUNA_MELEE));
        RenderingRegistry.registerEntityRenderingHandler(EntityBohemite.class, new RenderDivineMob(new Boheimite(), 0.0F, x.BOHEMITE));
        RenderingRegistry.registerEntityRenderingHandler(EntityWreck.class, new RenderWreck(new WreckForm1(), 0.0F, x.WRECK));
        RenderingRegistry.registerEntityRenderingHandler(EntityBiphron.class, new RenderBiphron(new Biphron(), 0.0F, x.BIPHRON));
        RenderingRegistry.registerEntityRenderingHandler(EntityHiveQueen.class, new RenderHiveQueen(new HiveQueen(), 0.0F, x.HIVE_QUEEN));
        RenderingRegistry.registerEntityRenderingHandler(EntityHiveSoldier.class, new RenderDivineMob(new HiveSoldier(), 0.0F, x.HIVE_SOLDIER));
        RenderingRegistry.registerEntityRenderingHandler(EntityLheiva.class, new RenderDivineMob(new Lheiva(), 0.0F, x.LHEIVA));
        RenderingRegistry.registerEntityRenderingHandler(EntityTwins.class, new RenderDivineMob(new Twins(), 0.0F, x.TWINS));
        RenderingRegistry.registerEntityRenderingHandler(EntityQuadro.class, new RenderDivineMob(new Quadro(), 0.0F, x.QUADRO));
        RenderingRegistry.registerEntityRenderingHandler(EntityEndiku.class, new RenderDivineMob(new Endiku(), 0.0F, x.ENDIKU));
        RenderingRegistry.registerEntityRenderingHandler(EntityTempleGuardian.class, new RenderDivineMob(new ModelBiped(), 0.0F, x.TEMPLE_GUARDIAN));
        RenderingRegistry.registerEntityRenderingHandler(EntityMysteriousManLayer1.class, new RenderDivineMob(new MysteriousMan(), 0.0F, x.MYSTERIOUS_MAN_LAYER_1));
        RenderingRegistry.registerEntityRenderingHandler(EntityMysteriousManLayer2.class, new RenderDivineMob(new MysteriousMan(), 0.0F, x.MYSTERIOUS_MAN_LAYER_2));
        RenderingRegistry.registerEntityRenderingHandler(EntityMysteriousManLayer3.class, new RenderDivineMob(new MysteriousMan(), 0.0F, x.MYSTERIOUS_MAN_LAYER_3));
        RenderingRegistry.registerEntityRenderingHandler(EntityCryptKeeper.class, new RenderDivineMob(new CryptKeeper(), 0.0F, x.CRYPT_KEEPER));
        RenderingRegistry.registerEntityRenderingHandler(EntityDuo.class, new RenderDivineMob(new Duo(), 0.0F, x.DUO));
        RenderingRegistry.registerEntityRenderingHandler(EntityEhu.class, new RenderDivineMob(new Ehu(), 0.0F, x.EHU));
        RenderingRegistry.registerEntityRenderingHandler(EntityHusk.class, new RenderDivineMob(new Husk(), 0.0F, x.HUSK));
        RenderingRegistry.registerEntityRenderingHandler(EntityVermsillion.class, new RenderDivineMob(new Versmillion(), 0.0F, x.VERMSILLION));
        RenderingRegistry.registerEntityRenderingHandler(EntityStoneGolem.class, new RenderDivineMob(new StoneGolem(), 0.0F, x.STONE_GOLEM));
        RenderingRegistry.registerEntityRenderingHandler(EntityGalroid.class, new RenderDivineMob(new Galroid(), 0.0F, x.GALROID));
        RenderingRegistry.registerEntityRenderingHandler(EntityHerbomancer.class, new RenderDivineMob(new Herbomancer(), 0.0F, x.HERBOMANCER));
        RenderingRegistry.registerEntityRenderingHandler(EntityKaros.class, new RenderDivineMob(new Karos(), 0.0F, x.KAROS));
        RenderingRegistry.registerEntityRenderingHandler(EntityLheiva.class, new RenderDivineMob(new Lheiva(), 0.0F, x.LHEIVA));
        RenderingRegistry.registerEntityRenderingHandler(EntityLorga.class, new RenderDivineMob(new Lorga(), 0.0F, x.LORGA));
        RenderingRegistry.registerEntityRenderingHandler(EntityLorgaFlight.class, new RenderDivineMob(new Lorgaflight(), 0.0F, x.LORGA_FLIGHT));
        RenderingRegistry.registerEntityRenderingHandler(EntityMandragora.class, new RenderDivineMob(new Mandragora(), 0.0F, x.MANDRAGORA));
        RenderingRegistry.registerEntityRenderingHandler(EntityRaglok.class, new RenderDivineMob(new RaglokGogdure(), 0.0F, x.RAGLOK));
        RenderingRegistry.registerEntityRenderingHandler(EntityTocaxin.class, new RenderDivineMob(new Tocaxin(), 0.0F, x.TOCAXIN));
        RenderingRegistry.registerEntityRenderingHandler(EntityHungerHungry.class, new RenderDivineMob(new ModelHungerHungry(), 0.0F, x.HUNGER_HUNGRY));


        RenderingRegistry.registerEntityRenderingHandler(EntityKazroticShot.class, new RenderBasicProjectile(x.KAZROTIC_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityZoragonBomb.class, new RenderBasicProjectile(x.ZORAGON_BOMB));
        RenderingRegistry.registerEntityRenderingHandler(EntityDissimentShot.class, new RenderBasicProjectile(x.DISSIMENT_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityTeakerDisk.class, new RenderTeakerDisc(VetheaItemHelper.teakerDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityAmthirmisDisk.class, new RenderTeakerDisc(VetheaItemHelper.amthrimisDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityDarvenDisk.class, new RenderTeakerDisc(VetheaItemHelper.darvenDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityCermileDisk.class, new RenderTeakerDisc(VetheaItemHelper.cermileDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityPardimalDisk.class, new RenderTeakerDisc(VetheaItemHelper.pardimalDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityQuadroticDisk.class, new RenderTeakerDisc(VetheaItemHelper.quadroticDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityKarosDisk.class, new RenderTeakerDisc(VetheaItemHelper.karosDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityHeliosisDisk.class, new RenderTeakerDisc(VetheaItemHelper.heliosisDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityArksianeDisk.class, new RenderTeakerDisc(VetheaItemHelper.arksianeDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntitySpinebackDisc.class, new RenderTeakerDisc(VetheaItemHelper.spinebackDisk));
        RenderingRegistry.registerEntityRenderingHandler(EntityVetheanArrow.class, new RenderBasicArrow(x.TEAKER_ARROW));
        RenderingRegistry.registerEntityRenderingHandler(EntityVetheanArrow2.class, new RenderBasicArrow(x.DARVEN_ARROW));
        RenderingRegistry.registerEntityRenderingHandler(EntityVetheanWarArrow.class, new RenderBasicArrow(x.PARMIDAL_ARROW));
        RenderingRegistry.registerEntityRenderingHandler(EntityVetheanWrathArrow.class, new RenderBasicArrow(x.KAROS_ARROW));
        RenderingRegistry.registerEntityRenderingHandler(EntityKarosCannonShot.class, new RenderBasicArrow(x.KAROS_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityVetheanCannonShot.class, new RenderBasicProjectile(x.VETHEAN_CANNON_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityEvernightProjectile.class, new RenderBasicProjectile(x.EVERNIGHT));
        RenderingRegistry.registerEntityRenderingHandler(EntityEversightProjectile.class, new RenderBasicProjectile(x.EVERSIGHT));
        RenderingRegistry.registerEntityRenderingHandler(EntityBouncingProjectile.class, new RenderBasicProjectile(x.BOUNCING_PROJECTILE));
        RenderingRegistry.registerEntityRenderingHandler(EntityWreckStrengthShot.class, new RenderBasicProjectile(x.EXPLOSIVE_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityWreckExplosiveShot.class, new RenderBasicProjectile(x.EXPLOSIVE_SHOT));
        RenderingRegistry.registerEntityRenderingHandler(EntityRaglokBomb.class, new RenderBasicProjectile(x.RAGLOK_BOMB));
        RenderingRegistry.registerEntityRenderingHandler(EntityMandragoraProjectile.class, new RenderBasicProjectile(x.MANDRAGORA_1));
       
    }
}
