package net.divinerpg.helper.config;

import java.io.File;

import net.divinerpg.helper.HelperBase;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

public class ConfigHelper extends HelperBase{
	
	static FMLPreInitializationEvent Event;
	
	public static void initConfig(FMLPreInitializationEvent event){
		Event = event;
		
		blockConfig();
		itemConfig();
	}
	
	public static int addBlock(String name){
		File file = new File(Event.getModConfigurationDirectory(), "DivineRPG.cfg");
		Configuration config = new Configuration(file);
		config.load();
		config.getBlock(name + "ID", blockID++ - (byte)256).getInt();
		config.save();
		return blockID++;
	}
	
	public static int addTerrainBlock(String Cat, String Name){
		File file = new File(Event.getModConfigurationDirectory(), "DivineRPG.cfg");
		Configuration config = new Configuration(file);
		config.load();
		config.getTerrainBlock(Cat, Name + "ID", genBlockID++, Cat).getInt();
		config.save();
		return genBlockID++;
	}
	
	public static int addItem(String name){
		File file = new File(Event.getModConfigurationDirectory(), "DivineRPG.cfg");
		Configuration config = new Configuration(file);
		config.load();
		config.getItem(name + "ID", itemID++).getInt();
		config.save();
		return itemID++;
	}
	
	public static int IceStoneID, TwilightStoneID, DraviteGrassID, DraviteDirtID, AzuriteGrassID, AzuriteDirtID, UviteGrassID;
	public static int UviteDirtID, MythrilGrassID, MythrilDirtID, AugiteGrassID, AugiteDirtID;
	public static int ArcanaGrassID, ArcanaDirtID, RupeeOreID, ArlemiteOreID, RealmiteOreID, NetheriteOreID, BloodGemOreID, BlueFireID;
	public static int DivineStoneID, RupeeBlockID, ArlemiteBlockID, RealmiteBlockID, NetheriteBlockID, ObsidianBlockID;
	public static int DivineLogID, DivinePlankID, DivineLeavesID, DivineMossyID, Spawner1ID, BedrockBlockID, DarkStoneID, TarID;
	public static int AquaLampID, ArlemiteLampID, BlazeLampID, BlueFireLampID, DivineLampID, DrakenLampID, DraviteLampID, EnderLampID, GoldLampID, LavaLampID;
	public static int LapisLampID, MilkyLampID, MoltenLampID, NetheriteLampID, RedstoneLampID, RupeeLampID, SlimeLightID, IceLampID, KrakenLampID, RealmiteLampID;
	public static int JungleStoneLampID, DiamondLampID, BlueTorchID, GreenTorchID, OrangeTorchID, PinkTorchID, PurpleTorchID, SkeletonTorchID;
	public static int SteelDoorID, BlueLightID, GreenLightID, PurpleLightID, RedLightID, YellowLightID, YellowCandyCaneID, CheckerBlockID;
	public static int SpiderPumpkinID, EnderPumpkinID, CreeperPumpkinID, SkeletonPumpkinID, BlazePumpkinID, ZombiePumpkinID, IceManPumpkinID, CyclopsePumpkinID;
	public static int GhastPumpkinID, FrostPumpkinID, EnderWatcherPumpkinID, JungleSpiderPumpkinID, HellSpiderPumpkinID;
	public static int BlueFenceID, BlueFenceOnID, RedFenceID, RedFenceOnID, GreenFenceID, GreenFenceOnID, IceGrassID, IceDirtID;
	public static int ayeracoBlueBeamID, ayeracoGreenBeamID, ayeracoRedBeamID, ayeracoPurpleBeamID, ayeracoYellowBeamID;
	public static int AntiNetherPortalID, CyanColouredVeinID, RedColouredVeinID, YellowColouredVeinID, PurpleColouredVeinID, GreenColouredVeinID;
	public static int AquaBricksID, ArlemiteBricksID, DarkStoneBricksID, DiamondBricksID, LapisLazuliBricksID, LavaBricksID;
	public static int MilkstoneBricksID, NetheriteBricksID, RealmiteBricksID, RedstoneBricksID, MilkstoneMiniBricksID;
	public static int AcceleraunchID, AccelleronID, PurpleStoneID, Light1ID, Light2ID, RainbowWoolID, TomatoCropID;
	public static int DirtBlockID, SoulSandBlockID, MilkstoneID, GreenCandyCaneID, PurpleCandyCaneID, BlueCandyCaneID, RedCandyCaneID;
	public static int StainedGlassID, StainedGlass1ID, StainedGlass2ID, StainedGlass3ID, StainedGlass4ID, StainedGlass5ID, StainedGlass6ID, StainedGlass7ID, SuperEnchantTableID;
	public static int DravitePortalID, AzuritePortalID, UvitePortalID, MythrilPortalID, AugitePortalID, DraviteBlockID;
	public static int AzuriteBlockID, UviteBlockID, MythrilBlockID, AugiteBlockID, DraviteOreID, AzuriteOreID;
	public static int UviteOreID, MythrilOreID, AugiteOreID, DraviteLogID, AzuriteLogID, UviteLogID, MythrilLogID, AugiteLogID;
	public static int DraviteLeavesID, AzuriteLeavesID, UviteLeavesID, MythrilLeavesID, AugiteLeavesID, AzuriteVineID;
	public static int IceikaPortalID, IceLogID, IceLeavesID, FrostStoneID, RolumSpawnerID, GlacideSpawnerID, WorkCarpetID, CoalstoneFurnaceOnID;
	public static int CoalStoneID, WorkLampID, SnowBrickID, IceBrickID, WorkBookcaseID, FrostGlassID, CoalstoneFurnaceID, FrostChestID;
	public static int ArcanaPortalID, blockOfLightID, MoltenFurnaceID, MoltenFurnaceOnID, OreDoor2BlockID, OreDoor3BlockID, OreDoor4BlockID;
	public static int MoonlightFurnaceID, MoonlightFurnaceOnID, OceanFireFurnaceID, OceanFireFurnaceOnID, WhiteFireFurnaceID;
	public static int WhiteFireFurnaceOnID, GreenLightFurnaceID, GreenLightFurnaceOnID, DemonFurnaceID, DemonFurnaceOnID;
	public static int ArcaniumOreID, StarBridgeOnID, StarBridgeID, ArcanaPortalFrameID, ExtractorID, HeatTrapOnID, HeatTrapID;
	public static int AncientBricksID, DegradedBricksID, ArcaniumMetalID, ArcaniumPowerID, AncientStoneID, SoulStoneID, DungeonLampID;
	public static int AncientTileID, SoulSludgeID, ParasectaAltarID, DramixAltarID, RoamerSpawnerID, DeathcryxSpawnerID, DeathHoundSpawnerID;
	public static int RazorbackSpawnerID, LivingStatueSpawnerID, DungeonPrisonerSpawnerID, ArcaniteTubesID, ArcaniteRailsID, OreDoor1BlockID;
	public static int KingStatueID, AncientStatueID, AyeracoStatueID, TwilightStatueID, VamacheronStatueID, DensosStatueID, DexStatueID, DramixStatueID, ParasectaStatueID, IceSaplingID;
	public static int SoulStatueID, WatcherStatueID, DraviteChestBlockID, fireStock2ID, pinFlyID, pinFly2ID, hitchakID, eucalyptusRootID, veiloID, lamonaID, aquamarineID, marsineID;
	
	public static int oreDoorItem1ID, oreDoor2ItemID, oreDoor3ItemID, oreDoor4ItemID, key1ID, key2ID, key3ID, key4ID, fireStockID;
	public static int hitchakintID, veilointID, lamonaintID, aquamarineintID, marsineintID, hitchakSeedsID, eucalyptusRootSeedsID;
	public static int veiloSeedsID, lamonaSeedsID, aquamarineSeedsID, marsineSeedsID, pinFlySeedsID, fireStockSeedsID;
	public static int arcaniumID, collectorID, fyracryxSpawnerID, fireflyID, starfallID, reflectorID, stormSwordID;
	public static int staffOfStarlightID, wraithbaneID, captiansSparklerID, shadowSwordID, enderScepterID, grenadeLauncherID;
	public static int grenadeID, meriksMissileID, arcaniumSaberID, liviciaSwordID, paratikuSpawnerID, seimerSpawnerID;
	public static int golemOfRejuvSpawnerID, dungeonTokenID, weakArcanaPotionID, strongArcanaPotionID, arcanaMusicBoxID;
	public static int orbOfLightID, collectorFragmentsID, arcaniumBucketID, tarBucketID, staffOfEnrichmentID, kormaHeadID, kormaBodyID;
	public static int kormaLegsID, kormaBootsID, vemosHeadID, vemosBodyID, vemosLegsID, vemosBootsID, wizardBookID;
	public static int fireStockItemID, pinFlyItemID, hitchakItemID, veiloItemID, lamonaItemID, aquamarineItemID, marsineItemID;
	public static int SnowflakeShurikenID, FrossivenceID, SerenadeOfIceID, GlacierSwordID, IcicleBowID, IceDoorID, IceDoorItemID;
	public static int IcicleBaneID, FrostclawCannonID, FractiteCannonID, FrostkingSwordID, SoundOfCarolsID, EndericeID;
	public static int SnowstormBowID, IcineSwordID, FrozenMaulID, SnowslashID, PeppermintsID, EggNogID, ChocolateLogID, SnowconesID;
	public static int FruitCakeID, SnowflakeID, SantaHeadID, SantaBodyID, SantaLegsID, SantaBootsID, fractiteCannonID;
	public static int DraviteGemID, DraviteChunkID, DraviteFragmentsID, DraviteDustID, DraviteBladeID, DravitePhaserID, DraviteBlitzID, DraviteBowID;
	public static int DraviteHelmetID, DraviteBootsID, DravitelegsID, DraviteChestID, DraviteSlicerID, DraviteSoulID, draviteSparklesID, DraviteShardsID;
	public static int UviteGemID, UviteChunkID, UviteFragmentsID, UviteDustID, UviteBladeID, UvitePhaserID;
	public static int UviteBlitzID, UviteBowID, UviteHelmetID, UviteBootsID, UvitelegsID, UviteChestID, UviteSlicerID, UviteSoulID;
	public static int AzuriteGemID, AzuriteChunkID, AzuriteFragmentsID, AzuriteDustID, AzuriteBladeID, AzuritePhaserID, AzuriteBlitzID, AzuriteBowID;
	public static int AzuriteHelmetID, AzuriteBootsID, AzuritelegsID, AzuriteChestID, AzuriteSlicerID, AzuriteSoulID, AzuriteArrowID;
	public static int MythrilGemID, MythrilChunkID, MythrilFragmentsID, MythrilDustID, MythrilBladeID, MythrilPhaserID, MythrilBlitzID, MythrilBowID;
	public static int MythrilHelmetID, MythrilBootsID, MythrillegsID, MythrilChestID, MythrilSlicerID, MythrilSoulID;
	public static int AugiteGemID, AugiteChunkID, AugiteFragmentsID, AugiteDustID, AugiteBladeID, AugitePhaserID;
	public static int AugiteBlitzID, AugiteBowID, AugiteHelmetID, AugiteBootsID, AugitelegsID, AugiteChestID, AugiteSlicerID, AugiteSoulID;
	public static int HaliteBladeID, HalitePhaserID, HaliteBlitzID, HaliteBowID, HaliteHelmetID, HaliteBootsID, HalitelegsID, HaliteChestID, HaliteSlicerID;
	public static int FuryArrowID, TwilightClockID, TwilightBowID, blueSeedsID, magicMeatID, empoweredMeatID;
	public static int enrichedMagicMeatID ,cookedEmpoweredMeatID, purpleSeedsID, pinkSeedsID, fireThrowerID, divineHelmID, divineBodyID, divineLegsID, divineBootsID;
	public static int DraviteShickaxeID, AzuriteShickaxeID, UviteShickaxeID, MythrilShickaxeID, AugiteShickaxeID, DivineShickaxeID; 
	public static int DraviteShovelID, DraviteAxeID, DravitePickaxeID, AugiteShovelID, AugiteAxeID, AugitePickaxeID;
	public static int AzuriteShovelID, AzuriteAxeID, AzuritePickaxeID, MythrilShovelID, MythrilAxeID, MythrilPickaxeID;
	public static int UviteShovelID, UviteAxeID, UvitePickaxeID, DivineShovelID, DivineAxeID, DivinePickaxeID;
	public static int BlueFireBowID, bedrockMaulID, soundOfMusicID, greenShardID, shurikenID, namkormiraID;
	public static int slimeSwordID,shadowBowID, crabClawCannonID, frostCannonID, frostSwordID, serenadeOfDeathID;
	public static int divineswordID, sandSlashID, iceShardID, yellowShardID, serenadeStrikerID, serenadeOfLifeID;
	public static int enderSwordID, enderSwordYellowID, enderSwordGreenID, enderSwordRedID, enderSwordBlueID;
	public static int enderSwordBlackID, bluefirebowID, rupeeID, tomatoID, tomatoSeedsID, purpleFireID;
	public static int jackOManBootsID, jackOManLegsID, jackOManBodyID, jackOManHeadID, scytheID, sharkAnchorID, healingStoneID;
	public static int sharkFinID, grimReaperHeadID, grimReaperBodyID, grimReaperLegsID, grimReaperBootsID, jungleStoneID;
	public static int divineStoneID, iceStoneID, enderStoneID, moltenStoneID, corruptedStoneID, blueFireStoneID, palavenceID;
	public static int arlemiteStabberID, rupeeRapierID, realmiteSwordID, poisonSaberID, infernoSwordID, bedrockSwordID;
	public static int aquaticDaggerID, aquaticTridentID, oceanKnifeID, aquatonID, sharkSwordID, crabclawMaulID, deathBringerID;
	public static int corruptedMaulID, scorchingSwordID, bluefireSwordID, divineSwordID, bloodgemSwordID, moltenSwordID;
	public static int vileStormID, crabAnchorID, bowheadCannonID, maelstromID, ghastCannonID, corruptCannonID, massivenceID;
    public static int seranadeDeathID, serenadeHealthID, growthSerenadeID, mailStromID, clawAnchorID, bowheadAnchorID;
    public static int vialStormID, infernobowID, crabClawMaulID, rupeeSwordID, passivenceID, angelicBodyID, angelicHeadID;
    public static int angelicLegsID, angelicBootsID, divineHeadID, purpleShardID, redShardID, corruptedShardsID, twilightClockID;
    public static int bloodGemID, arlemiteID, realmiteID, netheriteID, rupeeShovelID, rupeeAxeID, rupeeHoeID, rupeePickaxeID;
    public static int arlemiteShovelID, arlemiteAxeID, arlemiteHoeID, arlemitePickaxeID;
    public static int realmiteShovelID, realmiteAxeID, realmiteHoeID, realmitePickaxeID;
    public static int rupeeShickaxeID, arlemiteShickaxeID, TwilightAppleID;
    public static int hellStoneIngotID, purpleBlazeID, shadowBarID, netheriteChunkID, legendaryEnderEyeID;
    public static int realmiteHelmetID, realmiteBodyID, realmiteLegsID, realmiteBootsID;
    public static int arlemiteHelmetID, arlemiteBodyID, arlemiteLegsID, arlemiteBootsID;
    public static int rupeeHelmetID, rupeeBodyID, rupeeLegsID, rupeeBootsID;
    public static int infernalFlameID, baseSpawnCrystalID, SoulFiendSpawnCrystalID, VamacheronSpawnCrystalID;
    public static int TwilightDemonSpawnCrystalID, KarotSpawnCrystalID, DensosSpawnCrystalID;
    public static int hordeHornID, mysteriousClockID, watchingEyeID, callOfTheWatcherID, furyFireID;
    public static int shadowHelmetID, shadowBodyID, shadowLegsID, shadowBootsID;
    public static int aquaticHelmetID, aquaticBodyID, aquaticLegsID, aquaticBootsID;
    public static int krakenSkinID, krakenScaleID, shadowStoneID, homeTeleporterID; 
    public static int whaleFinID, purpleGlowTreeID, pinkGlowTreeID, crabClawID;
    public static int eliteRealHelmID, eliteRealBodyID, eliteRealLegsID, eliteRealBootsID;
    public static int krakenHelmID, krakenBodyID, krakenLegsID, krakenBootsID;
    public static int divineStickID, divineWoodAxeID, divineWoodPickID, divineWoodHoeID, divineWoodShovelID, divineWoodSwordID;
    public static int cyclopseEyeID, cyclopseBowID, cyclopseStaffID, cyclopseSwordID;
    public static int ironHelmID, ironBodyID, ironLegsID, ironBootsID, diamondHelmID, diamondBodyID, diamondLegsID, diamondBootsID;
    public static int aquaticStoneID, aquaticPelletsID, pureAquaticPelletsID, BedrockShovelID, BedrockAxeID, BedrockPickaxeID;
	public static int NetheriteHelmetID, NetheriteBodyID, NetheriteLegsID, NetheriteBootsID;
	public static int infernoHelmetID, infernoBodyID, infernoLegsID, infernoBootsID;
	public static int EnderHelmetID, EnderBodyID, EnderLegsID, EnderBootsID, BedrockHelmetID, BedrockBodyID, BedrockLegsID, BedrockBootsID;
	public static int donutID, mealID, pizzaDoughID, pizzaID, boiledEggID, baconID, cheeseID;
	
	public static void blockConfig(){
		
		DraviteGrassID = addTerrainBlock("Dravite", "Dravite Grass");
		DraviteDirtID = addTerrainBlock("Dravite", "Dravite Dirt");
		AzuriteGrassID = addTerrainBlock("Azurite", "Azurite Grass");
		AzuriteDirtID = addTerrainBlock("Azurite", "Azurite Dirt");
		UviteGrassID = addTerrainBlock("Uvite", "Uvite Grass");
		UviteDirtID = addTerrainBlock("Uvite", "Uvite Dirt"); 
		MythrilGrassID = addTerrainBlock("Mythril", "Mythril Grass");
		MythrilDirtID = addTerrainBlock("Mythril", "Mythril Dirt");
		AugiteGrassID = addTerrainBlock("Augite", "Augite Grass");
		AugiteDirtID = addTerrainBlock("Augite", "Augite Dirt");
		IceGrassID = addTerrainBlock("Iceika", "Iceika Grass");
		IceDirtID = addTerrainBlock("Iceika", "Iceika Dirt");
		IceStoneID = addTerrainBlock("Iceika", "Ice Stone");
		TwilightStoneID = addTerrainBlock("Twilight", "Twilight Stone");
		ArcanaGrassID = addTerrainBlock("Arcana", "Arcana Grass");
		ArcanaDirtID = addTerrainBlock("Arcana", "Arcana Dirt");
		
		RupeeOreID = addBlock("Rupee Ore");
		ArlemiteOreID = addBlock("Arlemite Ore");
		RealmiteOreID = addBlock("Realmite Ore");
		NetheriteOreID = addBlock("Netherite Ore");
		BloodGemOreID = addBlock("BloodGem Ore");
		BlueFireID = addBlock("Blue Fire");
		DivineStoneID = addBlock("Divine Stone");
		RupeeBlockID = addBlock("Rupee Block");
		ArlemiteBlockID = addBlock("Arlemite Block");
		RealmiteBlockID = addBlock("Realmite Block");
		NetheriteBlockID = addBlock("Netherite Block");
		ObsidianBlockID = addBlock("Obsidian Block");
		DivinePlankID = addBlock("Divine Plank");
		DivineMossyID = addBlock("Divine Mossy Cobblestone");
		Spawner1ID = addBlock("Jungle Dramcryx Spawner");
		DivineLeavesID = addBlock("Divine Leaves");
		DivineLogID = addBlock("Divine Log");
		AquaLampID = addBlock("Aqua Lamp");
		ArlemiteLampID = addBlock("Arlemite Lamp");
		BlazeLampID = addBlock("Blaze Lamp");
		BlueFireLampID = addBlock("BlueFire Lamp");
		DivineLampID = addBlock("Divine Lamp");
		DrakenLampID = addBlock("Draken Lamp");
		DraviteLampID = addBlock("Dravite Lamp");
		EnderLampID = addBlock("Ender Lamp");
		GoldLampID = addBlock("Gold Lamp");
		LavaLampID = addBlock("Lava Lamp");
		LapisLampID = addBlock("Lapis Lamp");
		MilkyLampID = addBlock("Milky Lamp");
		MoltenLampID = addBlock("Molten Lamp");
		NetheriteLampID = addBlock("Netherite Lamp");
		RedstoneLampID = addBlock("Redstone Lamp");
		RupeeLampID = addBlock("Rupee Lamp");
		SlimeLightID = addBlock("Slime Lamp");
		IceLampID = addBlock("Ice Lamp");
		KrakenLampID = addBlock("Kraken Lamp");
		RealmiteLampID = addBlock("Realmite Lamp");
		JungleStoneLampID = addBlock("JungleStone Lamp");
		DiamondLampID = addBlock("Diamond Lamp");
		BedrockBlockID = addBlock("Bedrock Block");
		DarkStoneID = addBlock("Dark Stone");
		SpiderPumpkinID = addBlock("Spider Pumpkin");
		EnderPumpkinID = addBlock("Ender Pumpkin");
		CreeperPumpkinID = addBlock("Creeper Pumpkin");
		SkeletonPumpkinID = addBlock("Skeleton Pumpkin");
		BlazePumpkinID = addBlock("Blaze Pumpkin");
		ZombiePumpkinID = addBlock("Zombie Pumpkin");
		IceManPumpkinID = addBlock("IceMan Pumpkin");
		CyclopsePumpkinID = addBlock("Cyclops Pumpkin");
		GhastPumpkinID = addBlock("Ghast Pumpkin");
		FrostPumpkinID = addBlock("Frost Pumpkin");
		EnderWatcherPumpkinID = addBlock("Ender Watcher Pumpkin");
		JungleSpiderPumpkinID = addBlock("Jungle Spider Pumpkin");
		HellSpiderPumpkinID = addBlock("Hell Spider Pumpkin");
		TarID = addBlock("Tar");
		BlueFenceID = addBlock("Blue Light Fence");
		BlueFenceOnID = addBlock("Blue Light Fence On");
		RedFenceID = addBlock("Red Light Fence");
		RedFenceOnID = addBlock("Red Light Fence On");
		GreenFenceID = addBlock("Green Fence");
		GreenFenceOnID = addBlock("Green Fence On");
		ayeracoBlueBeamID = addBlock("Blue Beam");
		ayeracoGreenBeamID = addBlock("Green Beam");
		ayeracoRedBeamID = addBlock("Red Beam");
		ayeracoPurpleBeamID = addBlock("Purple Beam");
		ayeracoYellowBeamID = addBlock("Yellow Beam");
		AntiNetherPortalID = addBlock("Anti-Nether Portal");
		GreenColouredVeinID = addBlock("Green Coloured Vane");
		PurpleColouredVeinID = addBlock("Purple Coloured Vane");
		YellowColouredVeinID = addBlock("Yellow Coloured Vane");
		RedColouredVeinID = addBlock("Red Coloured Vane");
		CyanColouredVeinID = addBlock("Cyan Coloured Vane");
		AquaBricksID = addBlock("Aqua Brick");
		ArlemiteBricksID = addBlock("Arlemite Brick");
		DarkStoneBricksID = addBlock("Darkstone Brick");
		DiamondBricksID = addBlock("Diamond Brick");
		LapisLazuliBricksID = addBlock("Lapis Brick");
		LavaBricksID = addBlock("Lava Brick");
		MilkstoneBricksID = addBlock("Milkstone Brick");
		NetheriteBricksID = addBlock("Netherite Brick");
		RealmiteBricksID = addBlock("Realmite Brick");
		RedstoneBricksID = addBlock("Redstone Brick");
		MilkstoneMiniBricksID = addBlock("Milkstone Mini Brick");
		AcceleraunchID = addBlock("Acceleraunch");
		AccelleronID = addBlock("Accelleron");
		PurpleStoneID = addBlock("Purple Stone");
		Light1ID = addBlock("Light 1");
		Light2ID = addBlock("Light 2");
		BlueTorchID = addBlock("Blue Torch");
		GreenTorchID = addBlock("Green Torch");
		OrangeTorchID = addBlock("Orange Torch");
		PinkTorchID = addBlock("Pink Torch");
		PurpleTorchID = addBlock("Purple Torch");
		SkeletonTorchID = addBlock("Skeleton Torch");
		BlueLightID = addBlock("Blue Xmas Light");
		GreenLightID = addBlock("Green Xmas Light");
		PurpleLightID = addBlock("Purple Xmas Light");
		RedLightID = addBlock("Red Xmas Light");
		YellowLightID = addBlock("Yellow Xmas Light");
		CheckerBlockID = addBlock("Checker Patten Block");
		RainbowWoolID = addBlock("Rainbow Wool");
		TomatoCropID = addBlock("Tomato Crop");
		DirtBlockID = addBlock("Dirt Block");
		SoulSandBlockID = addBlock("SoulSand Block");
		MilkstoneID = addBlock("Milkstone");
		GreenCandyCaneID = addBlock("Green CandyCane");
		PurpleCandyCaneID = addBlock("Purple CandyCane");
		BlueCandyCaneID = addBlock("Blue CandyCane");
		RedCandyCaneID = addBlock("Red CandyCane");
		YellowCandyCaneID = addBlock("Yellow CandyCane");
		StainedGlassID = addBlock("Stained Glass");
		StainedGlass1ID = addBlock("Stained Glass1");
		StainedGlass2ID = addBlock("Stained Glass2");
		StainedGlass3ID = addBlock("Stained Glass3");
		StainedGlass4ID = addBlock("Stained Glass4");
		StainedGlass5ID = addBlock("Stained Glass5");
		StainedGlass6ID = addBlock("Stained Glass6");
		StainedGlass7ID = addBlock("Stained Glass7");
		SuperEnchantTableID = addBlock("Super Enchantment Table");
		DravitePortalID = addBlock("Dravite Portal");
		AzuritePortalID = addBlock("Azurite Portal");
		UvitePortalID = addBlock("Uvite Portal");
		MythrilPortalID = addBlock("Mythril Portal");
		AugitePortalID = addBlock("Augite Portal");
		DraviteBlockID = addBlock("Dravite Block");
		AzuriteBlockID = addBlock("Azurite Block");
		UviteBlockID = addBlock("Uvite Block");
		MythrilBlockID = addBlock("Mythril Block");
		AugiteBlockID = addBlock("Augite Block");
		DraviteLeavesID = addBlock("Dravite Leaves");
		AzuriteLeavesID = addBlock("Azurite Leaves");
		UviteLeavesID = addBlock("Uvite Leaves");
		MythrilLeavesID = addBlock("Mythril Leaves");
		AugiteLeavesID = addBlock("Augite Leaves");
		DraviteLogID = addBlock("Dravite Log");
		AzuriteLogID = addBlock("Azurite Log");
		UviteLogID = addBlock("Uvite Log");
		MythrilLogID = addBlock("Mythril Log");
		AugiteLogID = addBlock("Augite Log");
		DraviteOreID = addBlock("Dravite Ore");
		AzuriteOreID = addBlock("Azurite Ore");
		UviteOreID = addBlock("Uvite Ore");
		MythrilOreID = addBlock("Mythril Ore");
		AugiteOreID = addBlock("Augite Ore");
		AzuriteVineID = addBlock("Azurite Vine");
		IceikaPortalID = addBlock("Iceika Portal");
		IceDoorID = addBlock("Ice Door");
		IceLogID = addBlock("Ice Log");
		IceLeavesID = addBlock("Ice Leaves");
		CoalStoneID = addBlock("Coalstone");
		WorkLampID = addBlock("Work Lamp");
		SnowBrickID = addBlock("Snowy Brick");
		IceBrickID = addBlock("Ice Brick");
		WorkBookcaseID = addBlock("WorkBook Case");
		FrostGlassID = addBlock("Frost Glass");
		CoalstoneFurnaceID = addBlock("CoalstoneFurnace Idle");
		FrostChestID = addBlock("Frost Chest");
		FrostStoneID = addBlock("Frost Stone");
		RolumSpawnerID = addBlock("Rolum Spawner");
		GlacideSpawnerID = addBlock("Glacide Spawner");
		WorkCarpetID = addBlock("Work Carpet");
		CoalstoneFurnaceOnID = addBlock("Coalstone Furnace On");
		ArcanaPortalID = addBlock("Arcana Portal");
		blockOfLightID = addBlock("Block Of Light");
		ArcanaPortalFrameID = addBlock("Arcana Portal Frame");
		MoltenFurnaceID = addBlock("Molten Furnace");
		MoltenFurnaceOnID = addBlock("Molten Furnace On");
		MoonlightFurnaceID = addBlock("Moonlight Furnace");
		MoonlightFurnaceOnID = addBlock("Moonlight Furnace On");
		OceanFireFurnaceID = addBlock("OceanFire Furnace");
		OceanFireFurnaceOnID = addBlock("OceanFire Furnace On");
		WhiteFireFurnaceID = addBlock("WhiteFire Furnace");
		WhiteFireFurnaceOnID = addBlock("WhiteFire Furnace On");
		GreenLightFurnaceID = addBlock("GreenLight Furnace");
		GreenLightFurnaceOnID = addBlock("GreenLight Furnace On");
		DemonFurnaceID = addBlock("DemonFurnace");
		DemonFurnaceOnID = addBlock("DemonFurnace On");
		fireStockID = addBlock("Firestock");
		fireStock2ID = addBlock("Firestock 2");
		pinFlyID = addBlock("Pinfly");
		pinFly2ID = addBlock("Pinfly 2");
		hitchakID = addBlock("Hitchak");
		eucalyptusRootID = addBlock("Eucalyptus Root");
		veiloID = addBlock("Veilo");
		lamonaID = addBlock("Lamona");
		aquamarineID = addBlock("Aquamarine");
		marsineID = addBlock("Marsine");
		ArcaniumOreID = addBlock("Arcanium Ore");
		StarBridgeID = addBlock("StarBridge");
		StarBridgeOnID = addBlock("StarBridge On");
		ExtractorID = addBlock("Extractor");
		HeatTrapID = addBlock("HeatTramp");
		HeatTrapOnID = addBlock("HeatTrap On");
		AncientBricksID = addBlock("Ancient Brick");
		DegradedBricksID = addBlock("Degraded Brick");
		ArcaniumMetalID = addBlock("Arcanium Metal");
		ArcaniumPowerID = addBlock("Arcanium Power");
		AncientStoneID = addBlock("Ancient Stone");
		SoulStoneID = addBlock("Soul Stone");
		DungeonLampID = addBlock("Dungeon Lamp");
		AncientTileID = addBlock("Ancient Tile");
		SoulSludgeID = addBlock("Soul Sludge");
		ParasectaAltarID = addBlock("Parasecta Altar");
		DramixAltarID = addBlock("Dramix Altar");
		RoamerSpawnerID = addBlock("Roamer Spawner");
		DeathcryxSpawnerID = addBlock("Deathcryx Spawner");
		DeathHoundSpawnerID = addBlock("DeathHound Spawner");
		RazorbackSpawnerID = addBlock("Razorback Spawner");
		LivingStatueSpawnerID = addBlock("LivingStatue Spawner");
		DungeonPrisonerSpawnerID = addBlock("DungeonPrisoner Spawner");
		ArcaniteTubesID = addBlock("Arcanite Tubes");
		ArcaniteRailsID = addBlock("Arcanite Rails");
		OreDoor1BlockID = addBlock("OreDoor 1");
		OreDoor2BlockID = addBlock("OreDoor 2");
		OreDoor3BlockID = addBlock("OreDoor 3");
		OreDoor4BlockID = addBlock("OreDoor 4");
		KingStatueID = addBlock("King Statue");
		AncientStatueID = addBlock("Ancient Statue");
		AyeracoStatueID = addBlock("Ayeraco Statue");
		TwilightStatueID = addBlock("Twilight Statue");
		VamacheronStatueID = addBlock("Vamacheron Statue");
		DensosStatueID = addBlock("Densos Statue");
		DexStatueID = addBlock("Dex Statue");
		DramixStatueID = addBlock("Dramix Statue");
		ParasectaStatueID = addBlock("Parasecta Statue");
		SoulStatueID = addBlock("Soul Statue");
		WatcherStatueID = addBlock("Watcher Statue");
		DraviteChestBlockID = addBlock("Dravite Chest");
		IceSaplingID = addBlock("Iceika Sapling");
	}
	
	public static void itemConfig(){
		tomatoID = addItem("Tomato");
		bedrockMaulID = addItem("Bedrock Maul");
		soundOfMusicID = addItem("Sound Of Music");
		greenShardID = addItem("Jungle Shard");
		redShardID = addItem("Molten Shard");
        corruptedShardsID = addItem("Corrupted Shards");
        iceShardID = addItem("Ice Shard");
		yellowShardID = addItem("Divine Shard");
		shurikenID = addItem("Shuriken");
		rupeeID = addItem("Rupee Ingot");
		namkormiraID = addItem("Namkormira");
		serenadeStrikerID = addItem("Serenade Striker");
		slimeSwordID = addItem("Slime Sword");
		shadowBowID = addItem("Shadow Bow");
		crabClawCannonID = addItem("Crabclaw Cannon");
		frostCannonID = addItem("Frost Cannon");
		frostSwordID = addItem("Frost Sword");
		divineswordID = addItem("Divine Sword");
		sandSlashID = addItem("Sand Slash");
		enderSwordID = addItem("Ender Sword");
		enderSwordBlueID = addItem("Ender Sword Blue");
		enderSwordBlackID = addItem("Ender Sword Black");
		enderSwordGreenID = addItem("Ender Sword Green");
		enderSwordRedID = addItem("Ender Sword Red");
		enderSwordYellowID = addItem("Ender Sword Yellow");
		BlueFireBowID = addItem("BlueFire Bow");
		tomatoSeedsID = addItem("Tomato Seeds");
		purpleFireID = addItem("Purple Fire");
		jackOManBootsID = addItem("Jack O Man Boots");
		jackOManLegsID = addItem("Jack O Man Legs");
		jackOManBodyID = addItem("Jack O Man Body");
		jackOManHeadID = addItem("Jack O Man Head");
		scytheID = addItem("Scythe");
		sharkAnchorID = addItem("Shark Anchor");
		healingStoneID = addItem("Healing Stone");
		massivenceID = addItem("Massivence");
		palavenceID = addItem("Palavence");
		arlemiteStabberID = addItem("Arlemite Stabber");
		rupeeRapierID = addItem("Rupee Sword");
		realmiteSwordID = addItem("Realmite Sword");
		poisonSaberID = addItem("Poison Saber");
		twilightClockID = addItem("Twilight Clock");
		seranadeDeathID = addItem("Seranade Death");
		serenadeHealthID = addItem("Serenade Health");
		growthSerenadeID = addItem("Growth Serenade");
		mailStromID = addItem("Mail Strom");
        clawAnchorID = addItem("Claw Anchor");
        bowheadAnchorID = addItem("Bowhead Anchor");
        crabClawMaulID = addItem("Crabclaw Maul");
        rupeeSwordID = addItem("Claw Anchor");
        passivenceID = addItem("Passivence");
        angelicBodyID = addItem("Angelic Body");
        angelicHeadID = addItem("Angelic Head");
        angelicLegsID = addItem("Angelic Legs");
        angelicBootsID = addItem("Angelic Boots");
        purpleShardID = addItem("Ender Shard");
        moltenSwordID = addItem("Molten Sword");
        bedrockSwordID = addItem("Bedrock Sword");
        bloodGemID = addItem("Blood Gem");
		arlemiteID = addItem("Arlemite Ingot");
		realmiteID = addItem("Realmite Ingot");
		netheriteID = addItem("Netherite Ingot");
		rupeeShovelID = addItem("Rupee Shovel");
		rupeeAxeID = addItem("Rupee Axe");
		rupeeHoeID = addItem("Rupee Hoe");
		rupeePickaxeID = addItem("Rupee Pickaxe");
		arlemiteShovelID = addItem("Arlemite Shovel");
		arlemiteAxeID = addItem("Arlemite Axe");
		arlemiteHoeID = addItem("Arlemite Hoe");
		arlemitePickaxeID = addItem("Arlemite Pickaxe");
		realmiteShovelID = addItem("Realmite Shovel");
		realmiteAxeID = addItem("Realmite Axe");
		realmiteHoeID = addItem("Realmite Hoe");
		realmitePickaxeID = addItem("Realmite Pickaxe");
		rupeeShickaxeID = addItem("Rupee Shickaxe");
		arlemiteShickaxeID = addItem("Arlemite Shickaxe");
		hellStoneIngotID = addItem("Hellstone Ingot");
		purpleBlazeID = addItem("Purple Blaze");
		shadowBarID = addItem("Shadow Bar");
		netheriteChunkID = addItem("Netherite Chunk");
		legendaryEnderEyeID = addItem("Legendary Ender Eye");
		realmiteHelmetID = addItem("Realmite Helmet");
		realmiteBodyID = addItem("Realmite Body");
		realmiteLegsID = addItem("Realmite Legs");
		realmiteBootsID = addItem("Realmite Boots");
		arlemiteHelmetID = addItem("Arlemite Helmet");
		arlemiteBodyID = addItem("Arlemite Body");
		arlemiteLegsID = addItem("Arlemite Legs");
		arlemiteBootsID = addItem("Arlemite Boots");
		grimReaperHeadID = addItem("Grim Reaper Helmet");
		grimReaperBodyID = addItem("Grim Reaper Body");
		grimReaperLegsID = addItem("Grim Reaper Legs");
		grimReaperBootsID = addItem("Grim Reaper Boots");
		rupeeHelmetID = addItem("Rupee Helmet");
		rupeeBodyID = addItem("Rupee Body");
		rupeeLegsID = addItem("Rupee Legs");
		rupeeBootsID = addItem("Rupee Boots");
		infernalFlameID = addItem("Infernal Flame");
		baseSpawnCrystalID = addItem("Base Spawn");
		SoulFiendSpawnCrystalID = addItem("SoulFiend Spawn");
		VamacheronSpawnCrystalID = addItem("Vamacheron Spawn");
		TwilightDemonSpawnCrystalID = addItem("TwilightDemon Spawn");
		KarotSpawnCrystalID = addItem("Karot Spawn");
		DensosSpawnCrystalID = addItem("Densos Spawn");
		hordeHornID = addItem("Horde Horn");
		mysteriousClockID = addItem("Mysterious Clock");
		watchingEyeID = addItem("Watching Eye");
		callOfTheWatcherID = addItem("Call Of The Watcher");
		furyFireID = addItem("Fury Fire");
		shadowHelmetID = addItem("Shadow Helmet");
		shadowBodyID = addItem("Shadow Body");
		shadowLegsID = addItem("Shadow Legs");
		shadowBootsID = addItem("Shadow Boots");
		aquaticHelmetID = addItem("Aquatic Helmet");
		aquaticBodyID = addItem("Aquatic Body");
		aquaticLegsID = addItem("Aquatic Legs");
		aquaticBootsID = addItem("Aquatic Boots");
		krakenSkinID = addItem("Kraken Skin");
		krakenScaleID = addItem("Kraken Scale");
		shadowStoneID = addItem("Shadow Stone");
		homeTeleporterID = addItem("Home Teleporter");
		whaleFinID = addItem("Whale Fin");
		purpleGlowTreeID = addItem("Purple Glow Tree");
		pinkGlowTreeID = addItem("Pink Glow Tree");
		eliteRealHelmID = addItem("Elite Real Helmet");
		eliteRealBodyID = addItem("Elite Real Body");
		eliteRealLegsID = addItem("Elite Real Legs");
		eliteRealBootsID = addItem("Elite Real Boots");
		krakenHelmID = addItem("Kraken Helm");
		krakenBodyID = addItem("Kraken Body");
		krakenLegsID = addItem("Kraken Legs");
		krakenBootsID = addItem("Kraken Boots");
		divineStickID = addItem("Divine Stick");
		divineWoodAxeID = addItem("Divine Wood Axe");
		divineWoodPickID = addItem("Divie Wood Pick");
		divineWoodHoeID = addItem("Divine Wood Hoe");
		divineWoodShovelID = addItem("Divine Wood Shovel");
		//divineWoodSwordID = addItem("Divine Wood Sword");//TODO Re add when ID stops conflicting with rupee ingot
		cyclopseEyeID = addItem("Cyclops Eye");
		cyclopseBowID = addItem("Cyclops Bow");
		cyclopseStaffID = addItem("Cyclopian Staff");
		cyclopseSwordID = addItem("Cyclopian Sword");
		TwilightAppleID = addItem("Twilight Apple");
		divineSwordID = addItem("Divine Sword");
		sharkFinID = addItem("Shark Fin");
		corruptedMaulID = addItem("Corrupted Maul");
		serenadeOfDeathID = addItem("serenadeOfDeath");
		infernoSwordID = addItem("Inferno Sword");
		serenadeOfLifeID = addItem("Serenade of Growth");
		deathBringerID = addItem("Death Bringer");
		corruptCannonID = addItem("Corrupted Cannon");
		sharkSwordID = addItem("Shark Sword");
		ghastCannonID = addItem("GhastCannon");
		aquatonID = addItem("Aquaton");
		bowheadCannonID = addItem("BowHead Cannon");
		oceanKnifeID = addItem("Ocean Knife");
		maelstromID = addItem("MaelStrom");
		aquaticTridentID = addItem("Aquatic Trident");
		crabAnchorID = addItem("Crab Anchor");
		infernobowID = addItem("Inferno Bow");
		aquaticDaggerID = addItem("Aquatic Dagger");
		crabClawMaulID = addItem("Crabclaw Maul");
		blueFireStoneID = addItem("BlueFire Stone");
		divineStoneID = addItem("Divine Stone");
		corruptedStoneID = addItem("Corrupted Stone");
		jungleStoneID = addItem("Jungle Stone");
		iceStoneID = addItem("Ice Stone");
		moltenStoneID = addItem("Molten Stone");
		enderStoneID = addItem("Ender Stone");
		vileStormID = addItem("Vile Storm");
		crabClawID = addItem("Crab Claw");
		ironHelmID = addItem("Iron Helmet");
		ironBodyID = addItem("Iron Body");
		ironLegsID = addItem("Iron Legs");
		ironBootsID = addItem("Iron Boots");
		diamondHelmID = addItem("Diamond Helmet");
		diamondBodyID = addItem("Diamond Body");
		diamondLegsID = addItem("Diamond Legs");
		diamondBootsID = addItem("Diamond Boots");
		aquaticStoneID = addItem("Aquatic Stone");
		aquaticPelletsID = addItem("Aquatic Pellets");
		pureAquaticPelletsID = addItem("Pure Aquatic Pellets");
		BedrockAxeID = addItem("Bedrock Axe");
		BedrockPickaxeID = addItem("Bedrock Pickaxe");
		BedrockShovelID = addItem("Bedrock Shovel");
		bloodgemSwordID = addItem("BloodGem Sword");
		NetheriteHelmetID = addItem("Netherite Helmet");
		NetheriteBodyID = addItem("Netherite Chest");
		NetheriteLegsID = addItem("Netherite Leggings");
		NetheriteBootsID = addItem("Netherite Boots");
		infernoHelmetID = addItem("Inferno Helmet");
		infernoBodyID = addItem("Inferno Chest");
		infernoLegsID = addItem("Inferno Leggings");
		infernoBootsID = addItem("Inferno Boots");
		EnderHelmetID = addItem("Ender Helmet");
		EnderBodyID = addItem("Ender Chest");
		EnderLegsID = addItem("Ender Leggings");
		EnderBootsID = addItem("Ender Boots");
		BedrockHelmetID = addItem("Bedrock Helmet");
		BedrockBodyID = addItem("Bedrock Chest");
		BedrockLegsID = addItem("Bedrock Leggings");
		BedrockBootsID = addItem("Bedrock Boots");
		DraviteGemID = addItem("Dravite Gem");
		DraviteChunkID = addItem("Dravite Chunk");
		DraviteFragmentsID = addItem("Dravite Fragments");
		DraviteDustID = addItem("Dravite Dust");
		DraviteBladeID = addItem("Dravite Blade");
		DravitePhaserID = addItem("Dravite Phaser");
		DraviteBlitzID = addItem("Dravite Blitz");
		DraviteBowID = addItem("Dravite Bow");
		DraviteHelmetID = addItem("Dravite Helmet");
		DraviteBootsID = addItem("Dravite Boots");
		DravitelegsID = addItem("Dravite Legs");
		DraviteChestID = addItem("Dravite Chest");
		DraviteSlicerID = addItem("Dravite Slicer");
		DraviteSoulID = addItem("Dravite Soul");
		draviteSparklesID = addItem("Dravite Sparkles");
		DraviteShardsID = addItem("Dravite Shards");
		AzuriteGemID = addItem("Azurite Gem");
		AzuriteChunkID = addItem("Azurite Chunk");
		AzuriteFragmentsID = addItem("Azurite Fragments");
		AzuriteDustID = addItem("Azurite Dust");
		AzuriteBladeID = addItem("Azurite Blade");
		AzuritePhaserID = addItem("Azurite Phaser");
		AzuriteBlitzID = addItem("Azurite Blitz");
		AzuriteBowID = addItem("Azurite Bow");
		AzuriteHelmetID = addItem("Azurite Helmet");
		AzuriteBootsID = addItem("Azurite Boots");
		AzuritelegsID = addItem("Azurite Legs");
		AzuriteChestID = addItem("Azurite Chest");
		AzuriteSlicerID = addItem("Azurite Slicer");
		AzuriteSoulID = addItem("Azurite Soul");
		AzuriteArrowID = addItem("Azurite Arrow");
		UviteGemID = addItem("Uvite Gem");
		UviteChunkID = addItem("Uvite Chunk");
		UviteFragmentsID = addItem("Uvite Fragments");
		UviteDustID = addItem("Uvite Dust");
		UviteBladeID = addItem("Uvite Blade");
		UvitePhaserID = addItem("Uvite Phaser");
		UviteBlitzID = addItem("Uvite Blitz");
		UviteBowID = addItem("Uvite Bow");
		UviteHelmetID = addItem("Uvite Helmet");
		UviteBootsID = addItem("Uvite Boots");
		UvitelegsID = addItem("Uvite Legs");
		UviteChestID = addItem("Uvite Chest");
		UviteSlicerID = addItem("Uvite Slicer");
		UviteSoulID = addItem("Uvite Soul");
		MythrilGemID = addItem("Mythril Gem");
		MythrilChunkID = addItem("Mythril Chunk");
		MythrilFragmentsID = addItem("Mythril Fragments");
		MythrilDustID = addItem("Mythril Dust");
		MythrilBladeID = addItem("Mythril Blade");
		MythrilPhaserID = addItem("Mythril Phaser");
		MythrilBlitzID = addItem("Mythril Blitz");
		MythrilBowID = addItem("Mythril Bow");
		MythrilHelmetID = addItem("Mythril Helmet");
		MythrilBootsID = addItem("Mythril Boots");
		MythrillegsID = addItem("Mythril Legs");
		MythrilChestID = addItem("Mythril Chest");
		MythrilSlicerID = addItem("Mythril Slicer");
		MythrilSoulID = addItem("Mythril Soul");
		AugiteGemID = addItem("Augite Gem");
		AugiteChunkID = addItem("Augite Chunk");
		AugiteFragmentsID = addItem("Augite Fragments");
		AugiteDustID = addItem("Augite Dust");
		AugiteBladeID = addItem("Augite Blade");
		AugitePhaserID = addItem("Augite Phaser");
		AugiteBlitzID = addItem("Augite Blitz");
		AugiteBowID = addItem("Augite Bow");
		AugiteHelmetID = addItem("Augite Helmet");
		AugiteBootsID = addItem("Augite Boots");
		AugitelegsID = addItem("Augite Legs");
		AugiteChestID = addItem("Augite Chest");
		AugiteSlicerID = addItem("Augite Slicer");
		AugiteSoulID = addItem("Augite Soul");
		HaliteBladeID = addItem("Halite Blade");
		HalitePhaserID = addItem("Halite Phaser");
		HaliteBlitzID = addItem("Halite Blitz");
		HaliteBowID = addItem("Halite Bow");
		HaliteHelmetID = addItem("Halite Helmet");
		HaliteBootsID = addItem("Halite Boots");
		HalitelegsID = addItem("Halite Legs");
		HaliteChestID = addItem("Halite Chest");
		HaliteSlicerID = addItem("Halite Slicer");
		FuryArrowID = addItem("Fury Arrow");
		TwilightClockID = addItem("Twilight Clock");
		TwilightBowID = addItem("Twilight Bow");
		blueSeedsID = addItem("Blue Seeds");
		magicMeatID = addItem("Magic Meat");
		empoweredMeatID = addItem("Empowered Meat");
		enrichedMagicMeatID = addItem("Enriched Magic Meat");
		cookedEmpoweredMeatID = addItem("Cooked Empowered Meat");
		purpleSeedsID = addItem("Purple Seeds");
		pinkSeedsID = addItem("Pink Seeds");		
		fireThrowerID = addItem("Fire Thrower");
		DraviteShickaxeID = addItem("Dravite Shickaxe");
		AzuriteShickaxeID = addItem("Azurite Shickaxe");
		UviteShickaxeID = addItem("Uvite Shickaxe");
		MythrilShickaxeID = addItem("Mythril Shickaxe");
		AugiteShickaxeID = addItem("Augite Shickaxe");
		DivineShickaxeID = addItem("Divine Shickaxe");
		divineHelmID = addItem("Divine Helm");
		divineBodyID = addItem("Divine Body");
		divineLegsID = addItem("Divine Legs");
		divineBootsID = addItem("Divine Boots");
		DraviteAxeID = addItem("Dravite Axe");
		DravitePickaxeID = addItem("Dravite Pickaxe");
		DraviteShovelID = addItem("Dravite Shovel");
		AugiteAxeID = addItem("Augite Axe");
		AugitePickaxeID = addItem("Augite Pickaxe");
		AugiteShovelID = addItem("Augite Shovel");
		AzuriteAxeID = addItem("Azurite Axe");
		AzuritePickaxeID = addItem("Azurite Pickaxe");
		AzuriteShovelID = addItem("Azurite Shovel");
		UviteAxeID = addItem("Uvite Axe");
		UvitePickaxeID = addItem("Uvite Pickaxe");
		UviteShovelID = addItem("Uvite Shovel");
		DivineAxeID = addItem("Divine Axe");
		DivinePickaxeID = addItem("Divine Pickaxe");
		DivineShovelID = addItem("Divine Shovel");
		MythrilAxeID = addItem("Mythril Axe");
		MythrilPickaxeID = addItem("Mythril Pickaxe");
		MythrilShovelID = addItem("Mythril Shovel");
		SnowflakeShurikenID = addItem("Snowflake Shuriken");
		FrossivenceID = addItem("Frossivence");
		SerenadeOfIceID = addItem("Serenade Of Ice");
		GlacierSwordID = addItem("Glacier Sword");
		IcicleBowID = addItem("Icicle Bow");
		IcicleBaneID = addItem("Icicle Bane");
		IceDoorItemID = addItem("Ice Door Item");
		FrostclawCannonID = addItem("Frostclaw Cannon");
		FractiteCannonID = addItem("Fractite Cannon");
		FrostkingSwordID = addItem("Frostking Sword");
		SoundOfCarolsID = addItem("Sound of Carols");
		EndericeID = addItem("Enderice");
		SnowstormBowID = addItem("Snowstorm Bow");
		IcineSwordID = addItem("Icine Sword");
		FrozenMaulID = addItem("Frozen Maul");
		SnowslashID = addItem("Snowslash");
		PeppermintsID = addItem("Peppermints");
		EggNogID = addItem("Egg Nog");
		ChocolateLogID = addItem("Chocolate Log");
		SnowconesID = addItem("Snowcones");
		FruitCakeID = addItem("Fruit Cake");
		SnowflakeID = addItem("Snowflake");
		SantaHeadID = addItem("Santa Head");
		SantaBodyID = addItem("Santa Body");
		SantaLegsID = addItem("Santa Legs");
		SantaBootsID = addItem("Santa Boots");
		fractiteCannonID = addItem("Fractite Cannon");
		key1ID = addItem("key 1");
		key2ID = addItem("key 2");
		key3ID = addItem("key 3");
		key4ID = addItem("key 4");
		oreDoorItem1ID = addItem("Ore Door item 1");
		oreDoor2ItemID = addItem("Ore Door item 2");
		oreDoor3ItemID = addItem("Ore Door item 3");
		oreDoor4ItemID = addItem("Ore Door item 4");
		hitchakItemID = addItem("Hitchak Item");
		fireStockItemID = addItem("Firestock Item");
		pinFlyItemID = addItem("Pinfly Item");
		veiloItemID = addItem("Veilo Item");
		lamonaItemID = addItem("Lamona Item");
		aquamarineItemID = addItem("Aquamarine Item");
		marsineItemID = addItem("Marsine Item");
		hitchakSeedsID = addItem("Hitchak Seeds");
		eucalyptusRootSeedsID = addItem("Eucalyptus Root Seeds");
		veiloSeedsID = addItem("Leilo Seeds");
		lamonaSeedsID = addItem("Lamona Seeds");
		aquamarineSeedsID = addItem("Aquamarine Seeds");
		marsineSeedsID = addItem("Marsine Seeds");
		pinFlySeedsID = addItem("Pinfly seeds");
		fireStockSeedsID = addItem("Firestock seeds");
		arcaniumID = addItem("Arcanium");
		fyracryxSpawnerID = addItem("Fyracryx Spawner");
		fireflyID = addItem("Firefly");
		starfallID = addItem("Starfall");
		reflectorID = addItem("Reflector");
		stormSwordID = addItem("StormSword");
		staffOfStarlightID = addItem("Staff Of Starlight");
		wraithbaneID = addItem("Wraithbane");
		captiansSparklerID = addItem("Captian's Sparkler");
		shadowSwordID = addItem("Shadow Sword");
		enderScepterID = addItem("EnderScepter");
		grenadeLauncherID = addItem("Grenade Launcher");
		grenadeID = addItem("Grenade");
		meriksMissileID = addItem("Meriks Missile");
		arcaniumSaberID = addItem("Arcanium Saber");
		paratikuSpawnerID = addItem("Paratiku Spawner");
		seimerSpawnerID = addItem("Seimer Spawner");
		golemOfRejuvSpawnerID = addItem("Golem Of Rejuv Spawner");
		dungeonTokenID = addItem("Dungeon Token");
		liviciaSwordID = addItem("Livicia Sword");
		vemosHeadID = addItem("Vemos Head");
		vemosBodyID = addItem("Vemos Body");
		vemosLegsID = addItem("Vemos Legs");
		vemosBootsID = addItem("Vemos Boots");
		kormaHeadID = addItem("Kormas Head");
		kormaBodyID = addItem("Korma Body");
		kormaLegsID = addItem("Korma Legs");
		kormaBootsID = addItem("Korma Boots");
		wizardBookID = addItem("Wizards Book");
		arcaniumBucketID = addItem("Arcanium bucket");
		tarBucketID = addItem("Tar Bucket");
		collectorID = addItem("Collector");
		collectorFragmentsID = addItem("Collector Fragments");
		orbOfLightID = addItem("Orb Of Light");
		weakArcanaPotionID = addItem("Weak Arcana Potion");
		strongArcanaPotionID = addItem("Strong Arcana Potion");
		staffOfEnrichmentID = addItem("Staff Of Enrichment");
		donutID = addItem("Donut");
		mealID = addItem("Dinner");
		
		pizzaDoughID = addItem("Pizza Dough");
		pizzaID = addItem("Pizza");
		boiledEggID = addItem("Boiled Egg");
		baconID = addItem("Bacon");
		cheeseID = addItem("Cheese");
		
	}
}